import {Engine,clamp,distance,normal} from './engine.js?v=6';
import {Renderer} from './render.js?v=6';
import {SPELLS,ZONES,AREAS,AREA_BY_ID,UPGRADES,DISCIPLINES,RARITIES,SLOT_NAMES} from './data.js?v=6';
import {Soundscape} from './sound.js?v=6';

import {statsText,sellValue,salvageValue} from './loot.js?v=6';
import {shopBody} from './shop-ui.js?v=6';

const $=id=>document.getElementById(id),SAVE_KEY='gouden-horizon-action-v3';
const renderer=new Renderer($('world'),$('minimap')),audio=new Soundscape();
let engine=new Engine('tide',31489),started=false,loaded=false,paused=false,last=0,lastSave=0,pendingShown=null,modalKind=null,previousFocus=null,noticeKey='',hudTick=0;
const keys=new Set(),pointer={x:innerWidth*.6,y:innerHeight*.5,active:false,shoot:false,right:false},stick={x:0,y:0},touch={fire:false};
const touchMode=window.matchMedia?.('(pointer: coarse)').matches||false;
const paths={
 frost:'M12 2v20M3 7l18 10M3 17 21 7M8 4l4 4 4-4M8 20l4-4 4 4',gale:'M3 8h12c6 0 6-7 1-6M2 12h17c5 0 5 7 0 7M4 16h7',gravity:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM2 12c0-5 20-5 20 0s-20 5-20 0ZM12 2c5 0 5 20 0 20s-5-20 0-20',
 tide:'M12 3C9 8 5 11 5 15a7 7 0 0 0 14 0c0-4-4-7-7-12Z M8 15a4 4 0 0 0 4 4',
 storm:'M13 2 5 14h6l-1 8 9-13h-7l1-7Z',ember:'M13 2c1 5-4 7-3 11-2-1-3-3-3-5-5 7-3 14 5 14 9 0 10-9 4-15 1 4-2 5-3 4',
 dash:'M3 7h8M1 12h8M3 17h8M13 4l7 8-7 8M9 12h11',heal:'M9 3h6v6h6v6h-6v6H9v-6H3V9h6V3Z',
 nova:'M12 2v4M12 18v4M2 12h4M18 12h4M5 5l3 3M16 16l3 3M5 19l3-3M16 8l3-3M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10',
 ultimate:'M12 2 21 7v10l-9 5-9-5V7l9-5ZM12 6v12M6 9l12 6M18 9 6 15',
 prism:'M12 2 21 12 12 22 3 12 12 2ZM3 12h18M12 2l-4 10 4 10 4-10-4-10Z',
 shield:'M12 2 21 6v6c0 5-5 8-9 10-4-2-9-5-9-10V6l9-4ZM8 12l3 3 5-6',
 leaf:'M20 3C4 1 1 14 8 19s15-3 12-16ZM4 21 17 8M10 14v5M14 10h5',
 inventory:'M6 7V4h12v3M3 7h18v14H3V7ZM3 12h18M10 10h4v5h-4v-5Z',
 pause:'M8 4v16M16 4v16',sound:'M3 9h4l5-5v16l-5-5H3V9ZM16 8a6 6 0 0 1 0 8M19 5a10 10 0 0 1 0 14',
 mute:'M3 9h4l5-5v16l-5-5H3V9ZM16 9l6 6M22 9l-6 6',mouse:'M8 2h8a4 4 0 0 1 4 4v12a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4ZM12 2v8M4 10h16',
 target:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10ZM12 1v5M12 18v5M1 12h5M18 12h5'
};
const itemIcon=item=>`<img class="painted-item" src="assets/items/${item.art||item.id}.webp" alt="" draggable="false">`;
const icon=name=>(SPELLS[name]||name==='ultimate')?`<img class="painted-spell" src="assets/items/skill-${name}.webp" alt="" draggable="false">`:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.prism}"/></svg>`;
const escape=text=>String(text).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const timeLabel=seconds=>`${Math.floor(seconds/60).toString().padStart(2,'0')}:${Math.floor(seconds%60).toString().padStart(2,'0')}`;
function saved(){try{return localStorage.getItem(SAVE_KEY);}catch{return null;}}
function save(){if(!started)return;try{const json=engine.serialize();if(json)localStorage.setItem(SAVE_KEY,json);}catch{ /* Private browsing may disable storage. The run remains playable. */ }}
function refreshContinue(){$('continue-game').hidden=!saved();}
function clearInput(){keys.clear();pointer.shoot=false;pointer.right=false;touch.fire=false;stick.x=stick.y=0;document.querySelector('#joystick i').style.transform='';}
function playable(){return started&&!paused&&!modalKind&&engine.state.mode==='playing';}
function showModal(kind,kicker,title,body,actions=[]){
 previousFocus=document.activeElement;clearInput();modalKind=kind;$('modal-layer').dataset.kind=kind;$('modal-close').hidden=['loot','dead','won'].includes(kind);$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal-actions').replaceChildren();
 for(const action of actions){const button=document.createElement('button');button.className=action.secondary?'secondary':'primary';button.textContent=action.label;button.disabled=Boolean(action.disabled);button.addEventListener('click',action.run);$('modal-actions').append(button);}
 $('modal-layer').hidden=false;queueMicrotask(()=>($('modal-body').querySelector('button')||$('modal-actions').querySelector('button'))?.focus());
}
function hideModal(){modalKind=null;$('modal-layer').hidden=true;pendingShown=null;previousFocus?.focus?.();clearInput();}
function choices(items,callback,meta=()=> ''){
 $('modal-body').innerHTML+=`<div class="choice-grid">${items.map((item,i)=>`<button class="choice" data-choice="${i}" data-rarity="${item.rarity||''}"><span class="icon ${item.slot?'item-art':''}" style="color:${SPELLS[item.id]?.color||RARITIES[item.rarity]?.color||'#ead2a0'}">${item.slot?itemIcon(item):icon(item.icon||item.id)}</span><strong>${escape(item.name)}</strong><p>${escape(item.text)}</p><small>${meta(item)}</small></button>`).join('')}</div>`;
 $('modal-body').querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>callback(Number(button.dataset.choice))));
 queueMicrotask(()=>$('modal-body').querySelector('button')?.focus());
}
function start(discipline,restore=false){
 try{engine=restore?Engine.restore(saved()):new Engine(discipline);}
 catch{showModal('error','OPSLAG','Deze expeditie kan niet worden geladen.','<p>Je kunt meteen een nieuwe expeditie starten.</p>',[{label:'Nieuwe expeditie',run:chooseDiscipline}]);return;}
 started=true;paused=false;hideModal();$('cover').hidden=true;renderer.reset(engine.state.player);audio.start();audio.setZone(engine.state.zone);$('tutorial').hidden=restore;noticeKey='';last=performance.now();save();updateHUD();
 if(!restore)showModal('arrival','ROTTERDAM · 2089','Drie kernen. Eén laatste route.','<p>Hitte, zeespiegelstijging en mislukte ingrepen hebben Nederland opgebroken. Het klimaatnet <strong>Aurelia</strong> kan lokale herstelprojecten weer verbinden, maar de drie kalibratiekernen liggen verspreid.</p><p>Je begint in de veilige handelspost op de Getijdenkade. Koop of versterk uitrusting met F of B, en ga door de open doorgang naar de Verdronken Ring. De andere routes komen vrij als je kernen bergt. Open de wereldkaart met <strong>M</strong> om een vrijgespeelde bestemming te kiezen. Versla in een arena eerst alle vijanden; daarna verschijnt de terugdoorgang naar het transitkamp. In de drie kerngebieden herstel je station A en B en versla je de kernbewaker.</p><p>Je begint met drie elementen. Bij level-up besteed je zelf een punt aan een nieuwe spreuk of een permanente verbetering. Nieuwe uitrusting bewaar je in de rugzak en plaats je zelf met <strong>I</strong>. Een nat doel geleidt storm; zon en water maken een stoomgolf. Lees de rode aanvalstekens en ontwijk voordat ze vol zijn.</p>',[{label:'Betreed de Getijdenkade',run:hideModal}]);
}
function chooseDiscipline(){
 if(!loaded)return;showModal('discipline','KIES JE VELDPAK','Wie draagt de horizon?', '<p>Alle veldpakken beheersen <strong>getij, storm en zon</strong>. Je specialisatie bepaalt je startvoordeel; gevonden uitrusting en afstellingen vormen de rest van je build.</p>',[{label:'Terug',secondary:true,run:hideModal}]);
 choices(DISCIPLINES,i=>start(DISCIPLINES[i].id),item=>escape(item.relic));
}
function showHelp(){
 showModal('help','VELDHANDLEIDING','Lees de wereld. Verander het gevecht.',`<p>Verken tien verbonden gebieden en twee optionele zijroutes. Reis bij een gouden doorgang met F. Herstel twee meetstations in elk kerngebied. Kalibreren roept twee golven bewakers op. Versla ze, verzamel uitrusting en bereik de regiokern. In Aurelia wacht een Wachter met drie aanvalsfases.</p><div class="controls-grid">${[
 ['WASD / pijlen','Bewegen — de camera volgt je.'],['Muis + links','Vaste hoofdaanval. Kies getij, storm of zon in K.'],['1 t/m 6 / klik','Voer de vaardigheid in dat slot direct uit. Houd een cijfer vast om te herhalen.'],['Q / rechtsklik','Je toegewezen rechter ability. Kies deze in K.'],['SPATIE / E','Ontwijken — 2 ladingen, kort onkwetsbaar.'],['F · H · R','Interactie · verband · volledig geladen kernpuls.'],['I · K · M · B','Uitrusting · vaardigheden · kaart · handel bij de post.'],['Touch','Beweeg met de stick. Houd de doelknop vast voor automatisch richten.']].map(([a,b])=>`<kbd>${a}</kbd><span>${b}</span>`).join('')}</div><div class="combo-guide"><div><strong style="color:#93e6e8">GETIJ → STORM</strong><p>+70% schade op natte doelen. Bliksem springt door naar nabije vijanden.</p></div><div><strong style="color:#ffca8f">GETIJ → ZON</strong><p>Een stoomgolf verdooft en raakt de groep. Zon verbrandt ook sporenvelden.</p></div></div><p style="margin-top:15px">Handel met F bij een veilige transitpost. Koop, verkoop en versterk je uitrusting. Arena’s openen pas na alle gevechten een terugdoorgang; de volgende route komt daarna vrij.</p><p>Rode waarschuwingen tonen waar de aanval <strong>zal</strong> raken. Blijf bewegen, ontwijk op tijd en laat je mana herstellen.</p>`,[{label:started?'Terug naar expeditie':'Begrepen',run:hideModal}]);
}
const slotNames=SLOT_NAMES;
const statNames={power:'Spreukschade',hp:'Max. leven',mana:'Max. mana',regen:'Mana/sec',speed:'Loopsnelheid',dash:'Ontwijkherstel',crit:'Kritieke kans',armor:'Bescherming',tide:'Getijschade',storm:'Stormschade',ember:'Zonneschade',wetTime:'Natduur',chain:'Extra kettingdoelen',comboCharge:'Kernpulsopbouw',recovery:'Leven/sec',leech:'Leven per kill',waterproof:'Waterbestendig',heatGuard:'Hittebescherming',burnTime:'Brandduur'};
const percentages=new Set(['power','speed','dash','crit','armor','tide','storm','ember','comboCharge','heatGuard','burnTime']);
function compareStats(item,old){return [...new Set([...Object.keys(item.stats),...Object.keys(old.stats)])].map(key=>{const delta=(item.stats[key]||0)-(old.stats[key]||0);return `<span class="stat-delta ${delta>0?'better':delta<0?'worse':''}">${escape(statNames[key]||key)} <b>${delta>0?'+':''}${percentages.has(key)?Math.round(delta*100)+'%':delta.toFixed(Number.isInteger(delta)?0:1)}</b></span>`;}).join('')||'<span class="stat-delta">Geen statverschil</span>';}
function gearCard(item,label){return `<article class="gear" data-rarity="${item.rarity}"><span>${escape(label)} · ${RARITIES[item.rarity].name}</span><i style="color:${RARITIES[item.rarity].color}">${itemIcon(item)}</i><strong>${escape(item.name)}</strong><p>${escape(statsText(item))}</p></article>`;}
function showEquipment(uid=null,slot=null){if(!started)return;const p=engine.state.player,stats=engine.stats(),bag=p.inventory.filter(item=>!slot||item.slot===slot),selected=p.inventory.find(i=>i.uid===uid)||bag[0];
 showModal('equipment','VELDPAK · NIVEAU '+p.level,'Rugzak & uitrusting',`<p class="menu-intro">Kies een vondst uit je rugzak. Bekijk het verschil en plaats het zelf in het passende slot.</p><div class="equipped-strip">${Object.entries(p.equipment).map(([key,item])=>`<button data-gear-slot="${key}" data-rarity="${item.rarity}" class="equipped ${key===slot?'selected':''}"><span>${itemIcon(item)}</span><small>${slotNames[key].toUpperCase()}</small><strong>${escape(item.name)}${item.enhance?' +'+item.enhance:''}</strong><em>${RARITIES[item.rarity].name} · NIV. ${item.level||1} · UITGERUST</em></button>`).join('')}</div><div class="gear-stats"><span>${Math.round(stats.maxHp)} leven</span><span>${Math.round(stats.maxMana)} mana</span><span>${stats.manaRegen.toFixed(1)} mana/sec</span><span><b>${Math.round(stats.moveSpeed)}</b> loopsnelheid (+${Math.round(stats.speed*100)}%)</span><span>${Math.round(stats.power*100)}% spreukbonus</span></div><div class="inventory-heading"><h3>Rugzak <small>${p.inventory.length} / 48 onderdelen</small></h3>${slot?'<button class="text-button" id="all-bag">Toon alles</button>':''}</div><div class="bag-grid">${bag.map(item=>`<button data-item="${item.uid}" data-rarity="${item.rarity}" class="bag-item ${item.uid===selected?.uid?'selected':''}"><span style="color:${RARITIES[item.rarity].color}">${itemIcon(item)}</span><strong>${escape(item.name)}</strong><small>${slotNames[item.slot]} · ${RARITIES[item.rarity].name} · NIV. ${item.level||1}</small></button>`).join('')||'<p class="empty-bag">Nog geen vondsten in deze selectie. Open de messing veldkisten met F.</p>'}</div>${selected?`<div class="equipment-comparison">${gearCard(p.equipment[selected.slot],'NU IN '+slotNames[selected.slot].toUpperCase())}${gearCard(selected,'IN RUGZAK · '+slotNames[selected.slot].toUpperCase())}</div><div class="stat-comparison">${compareStats(selected,p.equipment[selected.slot])}</div>`:''}`, [{label:'Verder',run:hideModal},{label:'Veldarchieven',secondary:true,run:showCodex}]);
 if(selected){const equip=document.createElement('button');equip.className='primary equip-action';equip.textContent=p.level<(selected.requiredLevel||1)?'Vereist niveau '+selected.requiredLevel:'Uitrusten in '+slotNames[selected.slot];equip.disabled=p.level<(selected.requiredLevel||1);equip.addEventListener('click',()=>{engine.equipItem(selected.uid);save();showEquipment(null,selected.slot);});$('modal-actions').prepend(equip);const recycle=document.createElement('button');recycle.className='secondary';recycle.textContent='Recycle geselecteerd · +'+salvageValue(selected)+' schroot';recycle.addEventListener('click',()=>{engine.recycleItem(selected.uid);save();showEquipment(null,slot);});$('modal-actions').append(recycle);}
 $('modal-body').querySelectorAll('[data-item]').forEach(b=>b.addEventListener('click',()=>showEquipment(Number(b.dataset.item),slot)));$('modal-body').querySelectorAll('[data-gear-slot]').forEach(b=>b.addEventListener('click',()=>showEquipment(null,b.dataset.gearSlot)));$('all-bag')?.addEventListener('click',()=>showEquipment());
}
function showShop(tab='buy',uid=null){
 if(!engine.canTrade())return;const s=engine.state,p=s.player;s.mode='modal';s.pending=s.pending?.type==='shop'?s.pending:{type:'shop'};
 const items=tab==='buy'?s.world.shop.stock:tab==='sell'?p.inventory:Object.entries(p.equipment).map(([slot,i])=>({...i,equippedSlot:slot})),selected=items.find(i=>i.uid===uid)||null;
 const actions=[{label:'Verder',run:closeJournal},{label:'Rugzak beheren',secondary:true,run:()=>{engine.closeModal();showEquipment();}},{label:'Verband kopen · 15 schroot',secondary:true,disabled:p.scrap<15||p.potions>=8,run:()=>{engine.buySupply();save();showShop(tab,uid);}}];
 if(selected)actions.unshift({label:tab==='buy'?'Kopen · '+selected.price+' schroot':tab==='sell'?'Verkopen · +'+sellValue(selected)+' schroot':selected.enhance>=3?'Maximaal versterkt':'Versterken naar +'+((selected.enhance||0)+1)+' · '+engine.forgeCost(selected)+' schroot',disabled:tab==='buy'?(p.scrap<selected.price||p.inventory.length>=48):tab==='forge'?(selected.enhance>=3||p.scrap<engine.forgeCost(selected)):false,run:()=>{if(tab==='buy')engine.buyItem(selected.uid);else if(tab==='sell')engine.sellItem(selected.uid);else engine.reinforce(selected.equippedSlot);save();showShop(tab,tab==='forge'?uid:null);}});
 showModal('shop','VEILIGE TRANSITPOST',s.world.camp.name,shopBody(engine,tab,selected)+(selected&&tab==='buy'?`<div class="equipment-comparison">${gearCard(p.equipment[selected.slot],'NU UITGERUST')}${gearCard(selected,'TE KOOP')}</div><div class="stat-comparison">${compareStats(selected,p.equipment[selected.slot])}</div>`:''),actions);
 $('modal-body').querySelectorAll('[data-shop-tab]').forEach(b=>b.addEventListener('click',()=>showShop(b.dataset.shopTab)));$('modal-body').querySelectorAll('[data-shop-item]').forEach(b=>b.addEventListener('click',()=>showShop(tab,Number(b.dataset.shopItem))));
}
function showSkills(selected=null){if(!started)return;const p=engine.state.player;
 showModal('skills','NIVEAU '+p.level+' · '+p.skillPoints+' PUNTEN','Kies je vaardigheden',`<p class="menu-intro">Elk level levert één punt. Leer een spreuk of verbeter je veldpak. Links blijft je vaste hoofdaanval. Kies een geleerde ability voor een cijfer-slot of de rechtermuisknop.</p><div class="attack-bindings"><strong>Vaste hoofdaanval · linkermuis</strong><div>${['tide','storm','ember'].map(id=>`<button data-main-attack="${id}" class="${p.mainAttack===id?'selected':''}"><span>${icon(id)}</span>${SPELLS[id].name}</button>`).join('')}</div><p>Rechts + Q: <b>${p.rightAbility==='element'?'Elementvaardigheid van '+SPELLS[p.mainAttack].short:SPELLS[p.rightAbility].name}</b></p><button data-right-ability="element" class="text-button">Stel standaard elementvaardigheid in</button></div><div class="skill-library">${Object.entries(SPELLS).map(([id,spell])=>{const learned=p.skills.includes(id),available=p.level>=(spell.unlockLevel||1);return `<button data-skill="${id}" class="skill-card ${id===selected?'selected':''}" ${!learned&&(!available||!p.skillPoints)?'disabled':''}><span style="color:${spell.color}">${icon(id)}</span><strong>${spell.name}</strong><small>${learned?'GELEERD'+(p.hotbar.includes(id)?' · SLOT '+(p.hotbar.indexOf(id)+1):' · NIET GEPLAATST')+(p.rightAbility===id?' · RM':''):available?'LEREN · 1 PUNT':'VRIJ VANAF LEVEL '+spell.unlockLevel}</small><p>${spell.description}</p></button>`;}).join('')}</div>${selected&&p.skills.includes(selected)?`<div class="assign-panel"><strong>${SPELLS[selected].name} plaatsen:</strong><div>${p.hotbar.map((id,i)=>`<button data-assign="${i}" class="${id===selected?'selected':''}"><kbd>${i+1}</kbd> ${id?SPELLS[id].short:'LEEG'}</button>`).join('')}</div><button data-right-ability="${selected}" class="primary">Op rechtermuis + Q plaatsen</button><small>Een cijfer voert deze ability uit. Je linkermuis blijft ${SPELLS[p.mainAttack].name}.</small></div>`:''}<h3>Permanente verbeteringen <small>1 punt per keuze</small></h3><div class="perk-grid">${UPGRADES.map(u=>`<button data-perk="${u.id}" ${p.skillPoints?'':'disabled'}><span>${icon(u.icon)}</span><strong>${u.name} ${p.perks[u.id]?'· '+p.perks[u.id]+'×':''}</strong><p>${u.text}</p></button>`).join('')}</div>`,[{label:'Verder',run:hideModal}]);
 $('modal-body').querySelectorAll('[data-main-attack]').forEach(b=>b.addEventListener('click',()=>{engine.setMainAttack(b.dataset.mainAttack);save();showSkills(selected);}));$('modal-body').querySelectorAll('[data-right-ability]').forEach(b=>b.addEventListener('click',()=>{engine.assignRight(b.dataset.rightAbility);save();showSkills(selected);}));
 $('modal-body').querySelectorAll('[data-skill]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.skill;if(!p.skills.includes(id))engine.purchaseUpgrade({id,skill:true});save();showSkills(id);}));$('modal-body').querySelectorAll('[data-assign]').forEach(b=>b.addEventListener('click',()=>{engine.assignSkill(selected,Number(b.dataset.assign));save();showSkills(selected);}));$('modal-body').querySelectorAll('[data-perk]').forEach(b=>b.addEventListener('click',()=>{engine.purchaseUpgrade(UPGRADES.find(u=>u.id===b.dataset.perk));save();showSkills(selected);}));
}
function showAtlas(){if(!started)return;const s=engine.state,goal=s.destination||engine.recommendedArea(),links=[],seen=new Set();for(const area of AREAS)for(const id of area.links){const key=[area.id,id].sort().join(':');if(!seen.has(key)){seen.add(key);links.push([area,AREA_BY_ID[id]]);}}
 showModal('atlas','WERELDKAART · '+s.visited.length+' / 10 ONTDEKT','Nederland, opnieuw verbonden',`<p class="menu-intro">Kies een bestemming voor de gouden richtingpijl. Reis zelf via de doorgangen met F. Kernen: ${s.cores.filter(c=>c<3).length}/3 · Bestemming: <strong>${AREA_BY_ID[goal].name}</strong></p><div class="world-atlas"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${links.map(([a,b])=>`<line x1="${a.map[0]}" y1="${a.map[1]}" x2="${b.map[0]}" y2="${b.map[1]}"/>`).join('')}</svg>${AREAS.map(a=>`<button ${!engine.isUnlocked(a.id)?'disabled':''} data-area="${a.id}" class="atlas-node ${s.area===a.id?'current':''} ${s.visited.includes(a.id)?'visited':''} ${goal===a.id?'destination':''}" style="left:${a.map[0]}%;top:${a.map[1]}%"><img src="assets/painted/${a.file}" alt=""><strong>${a.name}</strong><small>${s.area===a.id?'JE BENT HIER':!engine.isUnlocked(a.id)?'GEBLOKKEERD · '+a.unlockCore+' KERNEN NODIG':a.kind==='hub'?'KERNLOCATIE':a.id==='vault'||a.id==='rooftops'?'OPTIONELE VONDST':'TRANSIT · HANDELSPOST'}</small></button>`).join('')}</div>`,[{label:'Terug naar expeditie',run:hideModal}]);
 $('modal-body').querySelectorAll('[data-area]').forEach(b=>b.addEventListener('click',()=>{s.destination=b.dataset.area;engine.notice('Route naar '+AREA_BY_ID[s.destination].name);hideModal();save();}));
}
function showCodex(){const s=engine.state;showModal('codex','AURELIA · EXPEDITIELOG','Geen ingreep zonder terugkoppeling',s.codex.length?s.codex.map(log=>`<article class="codex-entry"><small>${escape(ZONES[log.zone].name)} · ${escape(log.title)}</small><p>${escape(log.body)}</p></article>`).join(''):'<p>Zoek de kleine veldarchieven in elke regio. Ze bewaren de kennis achter het klimaatnet.</p>',[{label:'Terug naar veldpak',run:showEquipment}]);}
function pauseMenu(){if(!started||engine.state.mode!=='playing')return;
 showModal('pause','EXPEDITIE GEPAUZEERD','De horizon wacht.',`<p>${escape(AREA_BY_ID[engine.state.area].name)} · ${timeLabel(engine.state.runTime)} onderweg</p><p>Je voortgang wordt automatisch in deze browser bewaard.</p>`,[{label:'Verder',run:hideModal},{label:'Besturing',secondary:true,run:showHelp},{label:'Titelmenu',secondary:true,run:()=>{save();hideModal();started=false;$('cover').hidden=false;refreshContinue();audio.pause();}}]);save();
}
function pendingModal(){const s=engine.state;if(s.pending&&s.pending!==pendingShown){const pending=s.pending;
 if(pending.type==='shop'){showShop();}else if(pending.type==='upgrade'){
  showModal('upgrade','LEVEL-UP · NIVEAU '+s.player.level+' · '+s.player.skillPoints+' PUNTEN','Maak je eigen build','<p>Leer een nieuwe spreuk of kies een permanente verbetering. Nieuwe aanvallen en gebiedsspreuken komen stapsgewijs vrij tot level 6. Je mag je punt bewaren.</p>',[{label:'Later kiezen · punt bewaren',secondary:true,run:()=>{engine.deferUpgrade();hideModal();save();}}]);choices(pending.choices,i=>{engine.chooseUpgrade(i);hideModal();save();},item=>item.skill?'NIEUWE SPREUK · AUTOMATISCH IN VRIJ SLOT':'PERMANENT · 1 PUNT');
 }else if(pending.type==='loot'){
  showModal('loot','VELDVONDST','Gebouwd uit wat overbleef.','<p>Kies één onderdeel voor je rugzak. Daarna kun je het verschil bekijken en zelf uitrusten, of het bewaren.</p>',[{label:'Alles recyclen · +14 schroot',secondary:true,run:()=>{engine.recycleLoot();hideModal();save();}}]);
  choices(pending.choices,i=>{const uid=engine.chooseLoot(i);if(!uid)return;hideModal();save();showEquipment(uid);},item=>`${RARITIES[item.rarity].name} · NIV. ${item.level||1} · ${escape(SLOT_NAMES[item.slot].toUpperCase())}<br>Huidig slot: ${escape(s.player.equipment[item.slot].name)}`);if(s.player.inventory.length>=48){$('modal-body').querySelectorAll('[data-choice]').forEach(b=>b.disabled=true);$('modal-kicker').textContent='RUGZAK VOL · RECYCLE DE VONDST';}
 }else if(pending.type==='archive'){
  showModal('archive','VELDARCHIEF',pending.title,`<p>${escape(pending.body)}</p>`,[{label:'Bewaar & verder',run:()=>{engine.closeModal();hideModal();save();}}]);

 }
 pendingShown=pending;save();
 }
 if(s.mode==='dead'&&modalKind!=='dead'){
  showModal('dead','SIGNALERING VERLOREN','De route is nog niet voorbij.',`<p>Je veldpak viel uit in ${escape(AREA_BY_ID[s.area].name)}. Herstart dit gebied vanaf je laatste aankomst. Andere gebieden blijven zoals ze op dat moment waren.</p><p>${s.kills} bewakers verslagen · ${s.combos} elementcombinaties · ${timeLabel(s.runTime)} onderweg</p>`,[{label:'Herstart gebied',run:()=>{engine.retry();hideModal();renderer.reset(engine.state.player);save();}},{label:'Titelmenu',secondary:true,run:()=>{engine.retry();save();hideModal();started=false;$('cover').hidden=false;refreshContinue();audio.pause();}}]);
 }
 if(s.mode==='won'&&modalKind!=='won'){
  try{localStorage.removeItem(SAVE_KEY);}catch{}
  showModal('won','AURELIA IS ONLINE','Een gouden horizon.',`<p>De lens leest. De oceaanverdeler koelt. De biosfeersleutel antwoordt. Voor het eerst in jaren werkt het klimaatnet als één systeem.</p><p>De correctie begint klein: meetbaar, omkeerbaar en onder lokaal toezicht. Morgen is weer bereikbaar.</p><div class="run-result"><strong>${s.score.toLocaleString('nl-NL')}</strong><span>EXPEDITIESCORE</span><p>${timeLabel(s.runTime)} · ${s.kills} bewakers · ${s.combos} combinaties · ${s.visited.length}/10 gebieden · ${s.codex.length}/4 archieven</p></div>`,[{label:'Terug naar handelskamp',run:()=>{engine.state.completed=true;engine.enterArea('skybridge');hideModal();renderer.reset(engine.state.player);save();}},{label:'Nieuwe expeditie',run:chooseDiscipline},{label:'Titelmenu',secondary:true,run:()=>{hideModal();started=false;$('cover').hidden=false;refreshContinue();audio.pause();}}]);
 }
}
function moveInput(){return {x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+stick.x,y:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+stick.y};}
function autoTarget(){const p=engine.state.player,near=engine.state.world.enemies.filter(e=>!e.dead&&distance(p,e)<650).sort((a,b)=>distance(p,a)-distance(p,b))[0];return near?{x:near.x,y:near.y-6}:{x:p.x+p.aim.x*250,y:p.y+p.aim.y*180};}
function target(){return touch.fire||touchMode?autoTarget():renderer.screenToWorld(pointer.x,pointer.y);}
function action(name){if(!playable())return;audio.start();let okay=true;
 if(name==='special')okay=engine.castRight(target());if(name==='dash'){const dir=moveInput();okay=engine.dash(dir.x,dir.y);}if(name==='heal')okay=engine.heal();if(name==='ultimate')okay=engine.ultimate();if(name==='interact'){okay=engine.interact();if(okay)save();}
 if(!okay&&name==='special')engine.notice(engine.inCamp()?'Veilige zone · verlaat het kamp om te casten':'Ability laadt op of heeft meer mana nodig');if(!okay&&name==='ultimate')engine.notice(engine.inCamp()?'Veilige zone · kernpuls buiten het kamp gebruiken':'Kernpuls laadt door schade en combinaties');
}
function updateHUD(){const s=engine.state,p=s.player,stats=engine.stats(),z=ZONES[s.zone],area=AREA_BY_ID[s.area];
 $('zone-place').textContent=z.subtitle.toUpperCase();$('zone-title').textContent=area.name;$('zone-count').textContent=`${String(s.visited.length).padStart(2,'0')} / 10`;$('run-time').textContent=timeLabel(s.runTime);$('terrain-text').textContent=z.rule;
 const defending=s.world.relays.filter(r=>r.status==='defending'),online=s.world.relays.filter(r=>r.status==='online').length;
 const remaining=s.world.enemies.filter(e=>!e.dead).length;
 $('quest-text').textContent=area.kind==='route'?area.story+' Handel bij aankomst met F of B.':s.world.coreCollected?'Gebied voltooid. De terugdoorgang blijft open.':engine.arenaCleared()?(s.zone===3?'Alle bewakers verslagen. Activeer Aurelia met F.':'Alles verslagen. Berg de kern bij de terugdoorgang en keer terug naar het handelskamp.'):s.zone===3?(s.world.bossDefeated?'Versla de laatste '+remaining+' bewakers.':'Versla de Gouden Wachter en zijn bewakers.'):s.world.gate.eliteSpawned?(s.world.enemies.some(e=>e.guardian&&!e.dead)?'Versla de kernbewaker en de laatste bewakers.':'Versla de laatste '+remaining+' bewakers om de terugweg te openen.'):defending.length?'Kalibratiegolf '+defending[0].wave+' / 2 · versla de bewakers.':online===1?'Herstel het tweede meetstation.':'Herstel de twee meetstations en versla alle bewakers.';
 $('relay-a').hidden=$('relay-b').hidden=area.kind!=='hub';s.world.relays.forEach(r=>{$('relay-'+r.id.toLowerCase()).className=r.status==='online'?'done':r.status==='defending'?'fighting':'';});$('core-icon').textContent=area.kind==='hub'?'◆ Kern':'↗ F · reizen';$('core-icon').className=s.world.coreCollected||s.world.coreAvailable?'done':'';
 $('hp-number').textContent=Math.ceil(p.hp);$('health-ring').style.strokeDashoffset=220*(1-p.hp/stats.maxHp);$('mana-bar').style.width=p.mana/stats.maxMana*100+'%';$('mana-number').textContent=`${Math.floor(p.mana)} / ${Math.round(stats.maxMana)}`;$('xp-bar').style.width=Math.min(100,p.xp/p.nextXp*100)+'%';$('level-label').textContent='NIV. '+p.level+(p.skillPoints?' · +'+p.skillPoints:'');$('skill-badge').hidden=!p.skillPoints;$('skill-badge').textContent=p.skillPoints;$('discipline-label').textContent='LINKS · '+SPELLS[p.mainAttack].short;$('scrap-label').textContent=p.scrap+' SCHROOT';$('status-label').textContent=engine.inCamp()?'VEILIGE ZONE':p.poison?'VERGIFTIGD':p.heat>2?'OVERHIT':p.wet?'NAT · VERTRAAGD':'STABIEL';
 const right=p.rightAbility==='element'?p.mainAttack:p.rightAbility,rightCd=p.rightAbility==='element'?p.skillCd:p.spellCd[right]||0,rightDuration=p.rightAbility==='element'?6:SPELLS[right].interval;
 if($('special-button').dataset.shownSkill!==right){$('special-button').querySelector('span').innerHTML=icon(right);$('special-button').dataset.shownSkill=right;}
 $('special-name').textContent=p.rightAbility==='element'?{tide:'Getijdengolf',storm:'Stormveld',ember:'Zonneveld'}[p.mainAttack]:SPELLS[right].short;$('special-cd').textContent=rightCd>0?rightCd.toFixed(1)+'s':(p.rightAbility==='element'?28:SPELLS[right].cost)+' mana';$('special-overlay').style.transform=`scaleY(${rightCd/rightDuration})`;$('dash-count').textContent=p.dashCharges+' / 2';$('dash-overlay').style.transform=`scaleY(${p.dashCharges?0:p.dashRecharge/stats.dashTime})`;$('potion-count').textContent=p.potions+' verband';$('ultimate-charge').textContent=Math.floor(p.ultimate)+'%';$('ultimate-overlay').style.transform=`scaleY(${1-p.ultimate/100})`;$('ultimate-button').classList.toggle('ready',p.ultimate>=100);$('ultimate-button').disabled=p.ultimate<100||engine.inCamp();$('shop-button').hidden=!engine.inCamp();
 document.querySelectorAll('[data-slot]').forEach(button=>{const id=p.hotbar[Number(button.dataset.slot)],spell=SPELLS[id];button.className='spell '+(id||'empty')+(id===p.lastAbility?' active':'');button.title=spell?spell.name+' — '+spell.description:'Leeg slot · open vaardigheden';if(button.dataset.shownSkill!==(id||'empty')){button.querySelector('.slot-icon').innerHTML=icon(id||'prism');button.dataset.shownSkill=id||'empty';}button.querySelector('.slot-name').textContent=spell?.short||'LEEG';button.querySelector('.slot-meta').textContent=spell?((p.spellCd[id]||0)>.05?p.spellCd[id].toFixed(1)+'s':spell.cost+' mana'):'K · leren';button.querySelector('.cooldown').style.transform=`scaleY(${spell?(p.spellCd[id]||0)/spell.interval:0})`;});
 const interact=engine.interaction();$('interaction').hidden=!interact;if(interact){$('interaction').querySelector('span').textContent=interact.label;if(touchMode)$('tutorial').hidden=true;}
 const boss=s.world.enemies.find(e=>e.type==='boss'&&!e.dead&&e.awake);$('boss-hud').hidden=!boss;if(boss){$('boss-life').style.width=boss.hp/boss.maxHp*100+'%';$('boss-phase').textContent='FASE '+['I','II','III'][boss.phase-1];$('tutorial').hidden=true;}
 const nk=s.notices.map(n=>n.text).join('|');if(nk!==noticeKey){noticeKey=nk;$('notices').innerHTML=s.notices.slice(0,2).map(n=>`<div style="color:${n.color}">${escape(n.text)}</div>`).join('');}
 if(!started||modalKind)$('aim-cursor').hidden=true;else $('aim-cursor').hidden=false;
}
function closeJournal(){if(modalKind==='upgrade')engine.deferUpgrade();if(['archive','shop'].includes(modalKind))engine.closeModal();hideModal();save();}
$('modal-close').addEventListener('click',closeJournal);$('shop-button').addEventListener('click',()=>playable()&&showShop());
$('new-game').disabled=true;$('new-game').addEventListener('click',chooseDiscipline);$('continue-game').addEventListener('click',()=>loaded&&start(null,true));$('cover-help').addEventListener('click',showHelp);$('equipment-button').addEventListener('click',()=>playable()&&showEquipment());$('skills-button').addEventListener('click',()=>playable()&&showSkills());$('level-label').addEventListener('click',()=>playable()&&showSkills());$('pause-button').addEventListener('click',()=>modalKind==='pause'?hideModal():pauseMenu());$('brand').addEventListener('click',event=>{event.preventDefault();pauseMenu();});$('sound-button').addEventListener('click',()=>{audio.start();const muted=audio.toggle();$('sound-button').innerHTML=icon(muted?'mute':'sound');$('sound-button').setAttribute('aria-label',muted?'Geluid inschakelen':'Geluid uitschakelen');});$('map-button').addEventListener('click',()=>playable()&&showAtlas());$('dismiss-tutorial').addEventListener('click',()=>$('tutorial').hidden=true);$('interaction').addEventListener('click',()=>action('interact'));
 document.querySelectorAll('[data-slot]').forEach(button=>button.addEventListener('click',()=>{if(!playable())return;const slot=Number(button.dataset.slot);if(!engine.state.player.hotbar[slot]){showSkills();return;}audio.start();if(!engine.castSlot(slot,autoTarget()))engine.notice(engine.inCamp()?'Veilige zone · verlaat het kamp om te casten':'Spreuk laadt op of heeft meer mana nodig');}));document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>action(button.dataset.action)));
window.addEventListener('keydown',event=>{
 const key=event.key.toLowerCase();if(playable()&&[' ','arrowup','arrowdown','arrowleft','arrowright'].includes(key))event.preventDefault();
 if(key==='tab'&&modalKind){const buttons=[...$('modal-layer').querySelectorAll('button:not(:disabled)')];if(buttons.length){const current=buttons.indexOf(document.activeElement),next=(current+(event.shiftKey?-1:1)+buttons.length)%buttons.length;event.preventDefault();buttons[next].focus();}return;}
 if(event.repeat)return;
 if(key==='escape'){if(['help','pause','equipment','skills','atlas','codex','discipline','arrival','error','upgrade','archive','shop'].includes(modalKind))closeJournal();else if(playable())pauseMenu();return;}
 if(!playable())return;keys.add(key);
 if(['1','2','3','4','5','6'].includes(key)){const slot=Number(key)-1;if(!engine.state.player.hotbar[slot])showSkills();else engine.castSlot(slot,pointer.active?target():autoTarget());}
 if(key==='q')action('special');if(key===' '||key==='e')action('dash');if(key==='h')action('heal');if(key==='r')action('ultimate');if(key==='f')action('interact');if(key==='i')showEquipment();if(key==='m')showAtlas();if(key==='k')showSkills();if(key==='b'&&engine.canTrade())showShop();
});window.addEventListener('keyup',event=>keys.delete(event.key.toLowerCase()));
$('world').addEventListener('pointermove',event=>{pointer.x=event.clientX;pointer.y=event.clientY;pointer.active=true;$('aim-cursor').style.left=pointer.x+'px';$('aim-cursor').style.top=pointer.y+'px';});
$('world').addEventListener('pointerdown',event=>{if(!playable())return;pointer.x=event.clientX;pointer.y=event.clientY;pointer.active=true;audio.start();if(event.button===0)pointer.shoot=true;if(event.button===2){action('special');pointer.right=true;}});window.addEventListener('pointerup',()=>{pointer.shoot=false;pointer.right=false;});$('world').addEventListener('contextmenu',event=>event.preventDefault());
$('world').addEventListener('wheel',event=>{if(!playable())return;event.preventDefault();const names=['tide','storm','ember'],index=names.indexOf(engine.state.player.spell);engine.selectSpell(names[(index+(event.deltaY>0?1:names.length-1))%names.length]);},{passive:false});
const joystick=$('joystick'),knob=joystick.querySelector('i');let stickPointer=null;
function moveStick(event){if(event.pointerId!==stickPointer)return;const rect=joystick.getBoundingClientRect(),dx=event.clientX-rect.left-rect.width/2,dy=event.clientY-rect.top-rect.height/2,len=Math.hypot(dx,dy),limit=Math.min(1,36/(len||1));knob.style.transform=`translate(${dx*limit}px,${dy*limit}px)`;stick.x=clamp(dx/36,-1,1);stick.y=clamp(dy/36,-1,1);}
joystick.addEventListener('pointerdown',event=>{if(!playable())return;event.preventDefault();stickPointer=event.pointerId;joystick.setPointerCapture(event.pointerId);moveStick(event);$('tutorial').hidden=true;});joystick.addEventListener('pointermove',moveStick);
function releaseStick(event){if(event.pointerId!==stickPointer)return;stickPointer=null;stick.x=stick.y=0;knob.style.transform='';}joystick.addEventListener('pointerup',releaseStick);joystick.addEventListener('pointercancel',releaseStick);
$('touch-fire').addEventListener('pointerdown',event=>{if(!playable())return;event.preventDefault();touch.fire=true;audio.start();$('touch-fire').setPointerCapture(event.pointerId);});for(const name of ['pointerup','pointercancel'])$('touch-fire').addEventListener(name,()=>touch.fire=false);
window.addEventListener('blur',()=>{clearInput();if(playable())pauseMenu();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(playable())pauseMenu();save();}});window.addEventListener('beforeunload',save);window.addEventListener('resize',()=>renderer.resize());
function frame(now){const delta=clamp((now-last)/1000,0,.04);last=now;if(loaded){
 if(playable()){const move=moveInput();let aim=pointer.active?renderer.screenToWorld(pointer.x,pointer.y):null;if(touch.fire)aim=autoTarget();engine.update(delta,{...move,aim,shoot:pointer.shoot||touch.fire,slots:['1','2','3','4','5','6'].filter(k=>keys.has(k)).map(k=>Number(k)-1),right:pointer.right});
  if(!pointer.active&&!touch.fire&&!['1','2','3','4','5','6'].some(k=>keys.has(k))&&engine.state.player.moving)engine.state.player.aim=normal(move.x,move.y);if(engine.state.runTime>12&&engine.state.runTime<13){$('tutorial-text').textContent='Maak vijanden nat met getij (1). Gebruik storm (2) voor kettingbliksem.';}
 }
 for(const event of engine.takeEvents()){audio.event(event);if(event.type==='zone'){renderer.reset(engine.state.player);audio.setZone(engine.state.zone);$('tutorial-text').textContent='F: doorgang of vondst · M: wereldkaart · K: vaardigheden · I: rugzak';}if(['special','combo'].includes(event.type))renderer.kick(2);if(event.type==='hurt'){renderer.kick(6);$('damage-flash').classList.add('hit');setTimeout(()=>$('damage-flash').classList.remove('hit'),180);}if(event.type==='ultimate')renderer.kick(5);if(event.type==='ultimpact')renderer.kick(13);}
 renderer.render(engine,now/1000,delta);if(started){pendingModal();hudTick+=delta;if(hudTick>.08){updateHUD();hudTick=0;}if(now-lastSave>8000){save();lastSave=now;}}
 }requestAnimationFrame(frame);}
refreshContinue();renderer.resize();requestAnimationFrame(frame);
renderer.load().then(()=>{loaded=true;renderer.reset(engine.state.player);$('new-game').disabled=false;$('load-status').textContent='Tien gebieden · tien spreuken · handel & uitrusting';}).catch(error=>{console.error(error);$('load-status').textContent='De spelbeelden konden niet laden. Vernieuw de pagina en probeer opnieuw.';});
