import {scoreStep} from './score.js?v=22';
// Original procedural score and spell sounds. No audio files or external requests.
export class Soundscape {
 constructor(){this.ctx=null;this.master=null;this.muted=false;this.zone=0;this.running=false;this.lastCast=0;this.timer=null;this.step=0;this.tension=0;this.music=null;this.fx=null;this.reverb=null;}
 start(){if(!this.ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;this.ctx=new Audio();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:.30;this.master.connect(this.ctx.destination);this.music=this.ctx.createGain();this.music.gain.value=.40;this.music.connect(this.master);this.fx=this.ctx.createGain();this.fx.gain.value=.55;this.fx.connect(this.master);
  this.reverb=this.ctx.createConvolver();const length=Math.round(this.ctx.sampleRate*2.8),impulse=this.ctx.createBuffer(2,length,this.ctx.sampleRate);let seed=1837;for(let channel=0;channel<2;channel++){const data=impulse.getChannelData(channel);for(let i=0;i<length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=(seed/2147483648-1)*Math.pow(1-i/length,3)*.35;}}this.reverb.buffer=impulse;const wet=this.ctx.createGain();wet.gain.value=.26;this.reverb.connect(wet);wet.connect(this.music);
 }this.applyVolumes();if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});if(!this.running){this.running=true;this.timer=setInterval(()=>this.ambient(),800);this.ambient();}}
 applyVolumes(){if(!this.ctx)return;this.music?.gain.setTargetAtTime(.4*(this.volumes?.music??.65),this.ctx.currentTime,.08);this.fx?.gain.setTargetAtTime(.55*(this.volumes?.effects??.8),this.ctx.currentTime,.08);}
 setVolumes(music,effects){this.volumes={music,effects};this.applyVolumes();}
 pause(){this.running=false;clearInterval(this.timer);this.timer=null;}
 toggle(){this.muted=!this.muted;if(this.master)this.master.gain.setTargetAtTime(this.muted?0:.30,this.ctx.currentTime,.15);return this.muted;}
 setZone(zone){this.zone=zone;this.step=0;}
 setTension(amount){this.tension+=(amount-this.tension)*.06;}
 tone(freq,duration=.2,type='sine',volume=.12,slide=0,delay=0){if(!this.ctx||!this.master||this.muted)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.fx||this.master);o.start(t);o.stop(t+duration+.03);o.onended=()=>{o.disconnect();g.disconnect();};}
 noise(duration=.18,volume=.12,cutoff=1800){if(!this.ctx||this.muted)return;const count=Math.ceil(this.ctx.sampleRate*duration),buffer=this.ctx.createBuffer(1,count,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<count;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/count,2);const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=cutoff;gain.gain.value=volume;source.connect(filter);filter.connect(gain);gain.connect(this.fx||this.master);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
 musicNote(note){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();o.type=note.kind==='pad'?'triangle':'sine';o.frequency.setValueAtTime(note.frequency,t);filter.type='lowpass';filter.frequency.value=note.kind==='pad'?650:1800;const attack=note.kind==='pad'?1.2:note.kind==='bell'?.035:.08;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(note.volume,t+attack);g.gain.exponentialRampToValueAtTime(.0001,t+note.duration);o.connect(filter);filter.connect(g);g.connect(this.music);if(note.kind!=='pulse')g.connect(this.reverb);o.start(t);o.stop(t+note.duration+.05);o.onended=()=>{o.disconnect();filter.disconnect();g.disconnect();};}
 ambient(){if(!this.running||this.muted)return;for(const note of scoreStep(this.zone,this.step++,this.tension))this.musicNote(note);}
 event(e){if(!this.running)return;const now=this.ctx?.currentTime||0;
 if(e.type==='cast'&&now-this.lastCast>.16){this.lastCast=now;if(e.spell==='tide'){this.noise(.12,.15,950);this.tone(430,.14,'sine',.1,-180);}else if(e.spell==='storm'||e.spell==='tempest'){this.tone(760,.12,'triangle',.075,-400);this.noise(.09,.075,5000);}else if((e.spell==='frost'||e.spell==='glacier'||e.spell==='prism')){this.tone(1100,.25,'sine',.1,450);this.noise(.12,.06,6000);}else if((e.spell==='gale'||e.spell==='cyclone')){this.noise(.3,.15,2200);this.tone(500,.2,'sine',.06,-220);}else if(e.spell==='gravity'){this.tone(100,.55,'sine',.14,-55);this.tone(220,.35,'triangle',.04,-100);}else{this.noise(.22,.18,700);this.tone(190,.2,'sine',.1,-100);}}
 if(e.type==='discovery'&&!e.collected){const notes=e.item.rarity==='legendary'?[392,523,659,1047]:e.item.rarity==='epic'?[392,587,784]:[440,659];for(const [i,n]of notes.entries())this.tone(n,.65,'sine',.065,0,i*.09);}
 if(e.type==='levelready'){for(const [i,n]of [523.25,659.25,783.99,1046.5].entries())this.tone(n,.85,'sine',.11,0,i*.14);}
 if(e.type==='summon'){this.tone(260,.4,'triangle',.07,140);this.tone(780,.3,'sine',.05);}if(e.type==='questcomplete'){this.tone(523,.45,'sine',.06);this.tone(784,.55,'sine',.04);}
 if(e.type==='enemyattack'){const notes={mines:220,magnet:90,echo:740,sweep:520,brinejet:130,saltwalls:180,shockwave:72,crossfire:620};this.noise(e.mode==='brinejet'?.25:.10,.06,e.mode==='brinejet'?2200:950);this.tone(notes[e.mode]||155,.18,'sine',.055,e.mode==='sweep'?110:-40);}
 if(e.type==='ultimpact'){this.noise(.65,.27,950);this.tone(73,.8,'sine',.18,-35);}if(e.type==='trade')this.tone(740,.22,'triangle',.05);
 if(e.type==='dash'){this.noise(.18,.13,1400);this.tone(230,.18,'sine',.07,270);}if(e.type==='hurt')this.tone(86,.18,'triangle',.2,-40);if(e.type==='combo'){this.tone(587,.35,'sine',.13);this.tone(880,.25,'sine',.07);}if(e.type==='special'){this.noise(.45,.17,1100);this.tone(293,.5,'triangle',.09,290);}if(e.type==='heal'){this.tone(523,.5,'sine',.1);this.tone(659,.6,'sine',.06);}if(['level','relaydone','loot'].includes(e.type)){this.tone(440,.6,'sine',.1);this.tone(659,.8,'sine',.06);}if(['ultimate','bossdead','win'].includes(e.type)){for(const n of [146,293,440,587])this.tone(n,1.5,'sine',.1);this.noise(.6,.13,1800);}
 }
}
