// Original procedural score and spell sounds. No audio files or external requests.
export class Soundscape {
 constructor(){this.ctx=null;this.master=null;this.muted=false;this.zone=0;this.running=false;this.lastCast=0;this.timer=null;this.step=0;}
 start(){if(!this.ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;this.ctx=new Audio();this.master=this.ctx.createGain();this.master.gain.value=.16;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});if(!this.running){this.running=true;this.timer=setInterval(()=>this.ambient(),1600);this.ambient();}}
 pause(){this.running=false;clearInterval(this.timer);this.timer=null;}
 toggle(){this.muted=!this.muted;if(this.master)this.master.gain.setTargetAtTime(this.muted?0:.16,this.ctx.currentTime,.15);return this.muted;}
 setZone(zone){this.zone=zone;this.step=0;}
 tone(freq,duration=.2,type='sine',volume=.12,slide=0){if(!this.ctx||!this.master||this.muted)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.03);o.onended=()=>{o.disconnect();g.disconnect();};}
 noise(duration=.18,volume=.12,cutoff=1800){if(!this.ctx||this.muted)return;const count=Math.ceil(this.ctx.sampleRate*duration),buffer=this.ctx.createBuffer(1,count,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<count;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/count,2);const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=cutoff;gain.gain.value=volume;source.connect(filter);filter.connect(gain);gain.connect(this.master);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
 ambient(){if(!this.running||this.muted)return;const roots=[146.83,130.81,164.81,174.61],root=roots[this.zone],notes=[1,1.5,2,1.25,1.5,1.125,2,1.5];this.tone(root*.5,2.7,'sine',.08);this.tone(root*notes[this.step++%notes.length],2.1,'sine',.055);if(this.step%4===0)this.tone(root*3,3,'sine',.03);}
 event(e){if(!this.running)return;const now=this.ctx?.currentTime||0;
 if(e.type==='cast'&&now-this.lastCast>.16){this.lastCast=now;if(e.spell==='tide'){this.noise(.12,.15,950);this.tone(430,.14,'sine',.1,-180);}else if(e.spell==='storm'||e.spell==='tempest'){this.tone(760,.12,'triangle',.075,-400);this.noise(.09,.075,5000);}else if((e.spell==='frost'||e.spell==='glacier')){this.tone(1100,.25,'sine',.1,450);this.noise(.12,.06,6000);}else if((e.spell==='gale'||e.spell==='cyclone')){this.noise(.3,.15,2200);this.tone(500,.2,'sine',.06,-220);}else if(e.spell==='gravity'){this.tone(100,.55,'sine',.14,-55);this.tone(220,.35,'triangle',.04,-100);}else{this.noise(.22,.18,700);this.tone(190,.2,'sine',.1,-100);}}
 if(e.type==='ultimpact'){this.noise(.65,.27,950);this.tone(73,.8,'sine',.18,-35);}if(e.type==='trade')this.tone(740,.22,'triangle',.05);
 if(e.type==='dash'){this.noise(.18,.13,1400);this.tone(230,.18,'sine',.07,270);}if(e.type==='hurt')this.tone(86,.18,'triangle',.2,-40);if(e.type==='combo'){this.tone(587,.35,'sine',.13);this.tone(880,.25,'sine',.07);}if(e.type==='special'){this.noise(.45,.17,1100);this.tone(293,.5,'triangle',.09,290);}if(e.type==='heal'){this.tone(523,.5,'sine',.1);this.tone(659,.6,'sine',.06);}if(['level','relaydone','loot'].includes(e.type)){this.tone(440,.6,'sine',.1);this.tone(659,.8,'sine',.06);}if(['ultimate','bossdead','win'].includes(e.type)){for(const n of [146,293,440,587])this.tone(n,1.5,'sine',.1);this.noise(.6,.13,1800);}
 }
}
