export const SPECIALIZATIONS={
 elementalist:{name:'Elementalist',art:'skill-tempest',text:'Bouw rond water, bliksem en vuur: sterker combineren of meer gebiedscontrole.',base:{tide:.06,storm:.06,ember:.06},tiers:[
  [{id:'conduction',name:'Geleider',text:'+15% stormschade en +1 seconde natduur.',stats:{storm:.15,wetTime:1}},{id:'firediscipline',name:'Vuurmeester',text:'+18% zonneschade en +20% brandduur.',stats:{ember:.18,burnTime:.2}}],
  [{id:'widefields',name:'Ruime velden',text:'Gebiedsspreuken hebben 15% groter bereik.',stats:{areaRadius:.15}},{id:'economy',name:'Zuivere stroming',text:'Elementspreuken kosten 12% minder mana.',stats:{manaEconomy:.12}}],
  [{id:'elements',name:'Elementkracht',text:'+12% getij-, storm- en zonneschade.',stats:{tide:.12,storm:.12,ember:.12}},{id:'reserves',name:'Diepe bron',text:'+25 mana en +3 mana per seconde.',stats:{mana:25,regen:3}}]
 ]},
 builder:{name:'Natuurhoeder',art:'skill-summon-v82',text:'Verbind je met levende dieren: een grotere roedel, meer aanvalskracht en bescherming.',base:{minionHealth:.10},tiers:[
  [{id:'overclock',name:'Wilde kracht',text:'Je dieren doen 25% meer schade.',stats:{minionDamage:.25}},{id:'plating',name:'Stevige huid',text:'Je dieren hebben 40% meer leven.',stats:{minionHealth:.4}}],
  [{id:'battery',name:'Diep verbond',text:'Je dieren krijgen 25% extra basisleven.',stats:{minionHealth:.25}},{id:'assembly',name:'Snelle oproep',text:'Oproepen kost 8 minder mana en herlaadt 3 seconden sneller.',stats:{summonDiscount:8,summonCooldown:3}}],
  [{id:'squad',name:'Roedel',text:'Vanaf niveau 10 krijgt je roedel een derde getijvos.',stats:{minionCount:1}},{id:'support',name:'Levenshoeder',text:'Lichtmot: maximaal 36 herstel. Moszwijn: 20% minder ontvangen schade.',stats:{menderCap:12,guardianGuard:.2}}]
 ]},
 hunter:{name:'Veldjager',art:'skill-prism',text:'Speel met gerichte schoten, sterke lansen en een snelle of beter beschermde veldjas.',base:{crit:.035},tiers:[
  [{id:'lances',name:'Lanskracht',text:'IJslans, Prismaboog en Donderlans doen 20% meer schade.',stats:{lancePower:.2}},{id:'cartridges',name:'Efficiënte foci',text:'Die drie lansen kosten 15% minder mana.',stats:{lanceEconomy:.15}}],
  [{id:'mobility',name:'Lichte uitrusting',text:'+12% loopsnelheid en 10% sneller ontwijkherstel.',stats:{speed:.12,dash:.1}},{id:'guard',name:'Veldpantser',text:'+7% bescherming en +15 maximaal leven.',stats:{armor:.07,hp:15}}],
  [{id:'precision',name:'Scherpe afstelling',text:'+8% kritieke kans.',stats:{crit:.08}},{id:'focus',name:'Krachtige focus',text:'+10% alle spreukschade en +10 maximaal mana.',stats:{power:.1,mana:10}}]
 ]}
};
export const TALENT_LEVELS=[5,8,11];
export const START_BUILDS=[
 {id:'elementalist',discipline:'tide',advantage:'+20 mana · +2 mana per seconde',progress:'Combineer getij, bliksem en vuur. Specialisatie en eerste talent vanaf niveau 5.'},
 {id:'builder',discipline:'ember',advantage:'+20 leven · +12% zonneschade',progress:'Leer één getijvos vanaf niveau 4. Je volledige dierenverbond opent op niveau 10.'},
 {id:'hunter',discipline:'storm',advantage:'+8% spreukschade · +5% kritieke kans',progress:'Gerichte schoten en sterke lansen. Kies kracht, snelheid of bescherming vanaf niveau 5.'}
];
export function specializationStats(p){const spec=SPECIALIZATIONS[p.specialization];if(!spec)return {};const out={...spec.base};for(let tier=0;tier<3;tier++){if(p.level<TALENT_LEVELS[tier])continue;const talent=spec.tiers[tier].find(t=>t.id===p.specializationTalents?.[tier]);for(const [key,value]of Object.entries(talent?.stats||{}))out[key]=(out[key]||0)+value;}return out;}
export function specializeSpell(p,id,spell){if(!spell)return spell;const stats=specializationStats(p),lance=['frost','prism','volt'].includes(id),has=effect=>Object.values(p.equipment||{}).some(i=>i.effect===effect);let out={...spell,cost:Math.max(1,Math.ceil(spell.cost*(1-(id!=='summon'?(lance?stats.lanceEconomy||0:0)+(stats.manaEconomy||0):0))-(id==='summon'?stats.summonDiscount||0:0))),interval:Math.max(.2,spell.interval-(id==='summon'?stats.summonCooldown||0:0)),damage:spell.damage*(1+(lance?stats.lancePower||0:0)),radius:spell.radius*(1+(spell.area?stats.areaRadius||0:0))};
 if(id==='ember'&&has('meteorStaff')){out={...out,name:'Sterrenmeteoor',cost:Math.ceil(12*1.55*(1-(stats.manaEconomy||0))),interval:.7*1.45,damage:30*1.7,variant:{id:'meteor',fan:1,blastRadius:175,fireRadius:80,flight:1.15,damage:1.7},description:'Eén zware gouden meteoor: 175 bereik, +70% schade, +55% mana en +45% herladen. Vervangt je bomvariant.'};}
 if(id==='summon'&&p.level>=10&&(p.companionProfile||'scout')==='scout'&&has('spiritAmber'))out={...out,cost:out.cost+12,interval:out.interval+4};return out;
}

export const SpecializationRules={
 chooseSpecialization(id){const p=this.state.player;if(p.level<5||!SPECIALIZATIONS[id]||p.specialization||this.challengeBuildLocked())return false;p.specialization=id;p.specializationTalents=[];this.notice(SPECIALIZATIONS[id].name+' gekozen · kies je talenten via K');this.emit('level');return true;},
 chooseTalent(tier,id){const p=this.state.player,spec=SPECIALIZATIONS[p.specialization];if(!spec||!Number.isInteger(tier)||tier<0||tier>2||p.level<TALENT_LEVELS[tier]||p.specializationTalents?.[tier]||!spec.tiers[tier].some(t=>t.id===id)||this.challengeBuildLocked())return false;const before=this.stats(),hp=p.hp/before.maxHp,mana=p.mana/before.maxMana;p.specializationTalents||=[];p.specializationTalents[tier]=id;p.hp=hp*this.stats().maxHp;p.mana=mana*this.stats().maxMana;this.emit('level');return true;},
 resetSpecialization(){const p=this.state.player;if(!p.specialization||!this.inCamp()||p.scrap<300||this.challengeBuildLocked())return false;const before=this.stats(),hp=p.hp/before.maxHp,mana=p.mana/before.maxMana;p.scrap-=300;p.specialization=null;p.preferredSpecialization=null;p.specializationTalents=[];p.hp=hp*this.stats().maxHp;p.mana=mana*this.stats().maxMana;this.checkpoint();return true;}
};
export function specializationMenu(p,safe){const chosen=SPECIALIZATIONS[p.specialization];return `<section class="specialization-menu"><h3>Specialisatie <small>Talenten op niveau 5 · 8 · 11</small></h3><p>Kies één richting. Elk niveau geeft één keuze in die rij, zonder vaardigheidspunt te kosten.</p><div class="specialization-options">${Object.entries(SPECIALIZATIONS).map(([id,s])=>`<button data-specialization="${id}" ${chosen||p.level<5?'disabled':''} aria-pressed="${id===p.specialization}"><img src="assets/items/${s.art}.webp" alt=""><strong>${s.name}</strong><p>${s.text}</p><small>${id===p.specialization?'ACTIEF':p.level<5?id===p.preferredSpecialization?'JOUW STARTKEUZE · ACTIEF VANAF 5':'VANAF NIVEAU 5':chosen?'ANDERE SPECIALISATIE':'KIES DEZE RICHTING'}</small></button>`).join('')}</div>${chosen?`<div class="talent-rows">${chosen.tiers.map((row,i)=>`<div><b>NIV. ${TALENT_LEVELS[i]}</b>${row.map(t=>`<button data-talent="${t.id}" data-talent-tier="${i}" ${p.level<TALENT_LEVELS[i]||p.specializationTalents?.[i]?'disabled':''} aria-pressed="${p.specializationTalents?.[i]===t.id}"><strong>${t.name}</strong><span>${t.text}</span></button>`).join('')}</div>`).join('')}</div><button data-respec="true" ${safe&&p.scrap>=300?'':'disabled'}>Specialisatie opnieuw kiezen · 300 schroot${!safe?' · bij een handelspost':''}</button>`:''}</section>`;}
