import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Engine,canStand,findPath,distance,copy,seeded} from '../src/engine.js';
import {STORY_ORDER} from '../src/story.js';
import {BIOME_AREAS,BIOME_ENEMIES} from '../src/biome-content.js';
import {arenaObstacles,coverHit} from '../src/arena-layouts.js';
import {attackProfile} from '../src/enemy-combat.js';
import {makeItem,makeUniqueItem,DROP_TABLES} from '../src/loot.js';
import {rollChaseItem,CHASE_DROPS} from '../src/chase-loot.js';
import {START_BUILDS,specializationMenu} from '../src/specializations.js';
import {UNIQUE_ITEMS} from '../src/unique-items.js';
import {Renderer} from '../src/render.js';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS '+name);};
function unlocked(id='groenkloof'){const g=new Engine('tide',681);g.state.cores=[0,1,2,3];g.state.storyPassed=STORY_ORDER.slice(0,21);assert(g.enterArea(id));return g;}
function walk(g,target){const p=g.state.player,path=findPath(p,target,g.state.area,35);assert(path.length,'unreachable '+(target.to||target.id));for(const q of path){let frames=0;while(distance(p,q)>5&&frames++<1600){const a=Math.round(Math.atan2((q.y-p.y)/.78,q.x-p.x)/(Math.PI/4))*Math.PI/4;g.update(1/60,{x:Math.round(Math.cos(a)),y:Math.round(Math.sin(a))});}assert(frames<1600,'stalled '+(target.to||target.id));}assert(distance(p,target)<8);}
function clear(g){for(const e of g.state.world.enemies.filter(e=>!e.dead))g.killEnemy(e);g.state.player.xp=0;g.update(.01);}
function shooting(){const g=new Engine();g.enterArea('ring');g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(g.state.player,{x:850,y:640,invincible:0});return g;}
test('New biomes unlock at Koelhof and routing leads through the actual green gateway',()=>{const g=new Engine();assert(!g.isUnlocked('groenkloof'));assert(!g.enterArea('glass-dunes'));g.state.cores=[0,1,2,3];g.state.storyPassed=STORY_ORDER.slice(0,21);g.enterArea('cooling-refuge');assert(g.isUnlocked('groenkloof'));assert.deepEqual(g.routeTo('glass-dunes'),['cooling-refuge','groenkloof','glass-dunes']);assert(g.state.world.portals.some(p=>p.to==='groenkloof'&&!p.locked));g.enterArea('groenkloof');assert.deepEqual(g.routeTo('heatworks'),['groenkloof','cooling-refuge','heatworks']);assert.equal(g.state.world.enemies.length,0);assert(g.inCamp());});
test('Every green merchant, gate, chest and overlook can be reached by actual eight-direction keyboard walking',()=>{const g=unlocked();const targets=[...g.state.world.portals,...g.hubMerchants(),...g.state.world.loot,...[[1280,200],[300,335],[925,780]].map(([x,y])=>({x:x*1.25,y:y*1.25}))];for(const p of targets){assert(canStand(p.x,p.y,35,'groenkloof'));walk(g,p);}const gates=g.state.world.portals;assert(distance(gates[0],gates[1])>900);});
test('Dunes require two enemy groups and one solo boss; completion pays once and re-entry preserves resources',()=>{const g=unlocked('glass-dunes'),w=g.state.world,p=g.state.player;assert.equal(w.enemies.length,5);assert(!g.portalReady());assert.equal(w.portals.length,1);assert.equal(w.portals[0].to,'groenkloof');clear(g);assert.equal(w.biome.wave,2);assert.equal(w.enemies.filter(e=>!e.dead).length,6);assert(!g.portalReady());clear(g);assert.equal(w.biome.wave,3);assert.deepEqual(w.enemies.filter(e=>!e.dead).map(e=>e.type),['dunebreaker']);assert(!g.portalReady());clear(g);assert(g.portalReady());const cash=p.scrap;assert(!g.completeBiomeArena());assert.equal(p.scrap,cash);assert.equal(g.state.biomeVictories['glass-dunes'],1);g.enterArea('groenkloof');p.hp=51;p.mana=25;p.potions=1;p.antidotes=0;const chests=g.state.world.loot.length;g.enterArea('glass-dunes');assert.equal(p.hp,51);assert.equal(p.mana,25);assert.equal(p.potions,1);assert.equal(p.antidotes,0);assert.equal(p.scrap,cash);assert.equal(g.state.world.biome.wave,1);g.enterArea('groenkloof');assert.equal(g.state.world.loot.length,chests);});
test('Dune cover blocks grounded fire and every spawn, loot and exit stays accessible',()=>{const g=unlocked('glass-dunes');for(let wave=0;wave<3;wave++){for(const e of g.state.world.enemies.filter(e=>!e.dead)){assert(canStand(e.x,e.y,e.radius,g.state.area));assert(findPath(g.state.player,e,g.state.area,18).length);}clear(g);}for(const p of [...g.state.world.portals,...g.state.world.loot]){assert(canStand(p.x,p.y,22,g.state.area));assert(findPath(g.state.player,p,g.state.area,22).length);}const o=arenaObstacles(g.state.area)[0];assert(coverHit({x:o.x-250,y:o.y},{x:o.x+250,y:o.y},g.state.area));assert(!canStand(o.x,o.y,18,g.state.area));});
test('Four distinct enemy attack sets release visible attacks and use the right element',()=>{const g=shooting();for(const type of Object.keys(BIOME_ENEMIES)){const e=g.makeEnemy(type,1100,640,false,true),modes=new Set();for(let i=0;i<(type==='dunebreaker'?3:2);i++){g.planAttack(e);modes.add(e.windup.mode);const mode=e.windup.mode,before=g.state.effects.length;g.executeEnemyAttack(e);assert(g.state.effects.length>before);if(mode==='cinderLob'){assert.equal(attackProfile(e).element,'fire');assert(g.state.projectiles.filter(p=>p.source===e.id).every(p=>p.element==='fire'));}e.windup=null;}assert.equal(modes.size,type==='dunebreaker'?3:2);}});
test('Quick skirmisher fire locks aim, has no floor marker, damages standing targets and misses a sidestep',()=>{function shot(dodge){const g=shooting(),e=g.makeEnemy('dustskirmisher',1150,640,false,true);g.planAttack(e);assert(e.windup.quick);assert(e.windup.total<=.35);Renderer.prototype.drawTelegraphs.call({ctx:{},drawV6Warning(){assert.fail('quick attack draws floor marker');}},{world:{enemies:[e]}});const target=copy(e.windup.target),hp=g.state.player.hp;if(dodge)g.state.player.y+=130;assert.deepEqual(e.windup.target,target);g.executeEnemyAttack(e);assert.equal(g.state.projectiles.length,1);for(let i=0;i<90;i++)g.updateProjectiles(1/60);return hp-g.state.player.hp;}assert(shot(false)>0);assert.equal(shot(true),0);});
test('Scorpion venom is painful over time; suitable armor meaningfully reduces it',()=>{function poison(resist){const g=shooting(),p=g.state.player;p.stats.poisonResist=resist;const hp=p.hp;assert(g.applyVenom());for(let i=0;i<8;i++)g.updateSurvival(1);return (hp-p.hp)/g.stats().maxHp;}assert(Math.abs(poison(0)-.5)<1e-9);assert(Math.abs(poison(.3)-.35)<1e-9);});
test('Boss phase accelerates attacks once and save/restore preserves frozen encounter strength',()=>{const g=unlocked('glass-dunes');clear(g);clear(g);const e=g.state.world.enemies.find(e=>!e.dead);e.hp=e.maxHp*.49;const cd=e.cooldownMultiplier;g.updateBiomeEnemy(e);assert.equal(e.phase,2);assert(e.cooldownMultiplier<cd);const next=e.cooldownMultiplier;g.updateBiomeEnemy(e);assert.equal(e.cooldownMultiplier,next);g.state.player.level=25;const r=Engine.restore(g.serialize()).state.world.enemies.find(e=>!e.dead);for(const key of ['hp','maxHp','damageMultiplier','cooldownMultiplier','phase'])assert.equal(r[key],e[key]);});
test('Starting build activates its selected specialization at level five and leaves talents manual',()=>{for(const b of START_BUILDS){const g=new Engine(b.discipline),p=g.state.player;p.preferredSpecialization=b.id;p.level=4;p.xp=p.nextXp;assert(specializationMenu(p,true).includes('JOUW STARTKEUZE'));g.update(.01);assert.equal(p.level,5);assert.equal(p.specialization,b.id);assert.equal(p.specializationTalents.length,0);assert.equal(Engine.restore(g.serialize()).state.player.preferredSpecialization,b.id);}});
test('Enemy loot preferences differ; exceptional items remain below two percent per actual item drop',()=>{for(const type of ['glassscorpion','dustskirmisher','slagcarrier']){const rng=seeded(419),table=DROP_TABLES[type];let preferred=0;for(let i=0;i<2000;i++){const item=makeItem({rng,level:18,profile:type,uid:i});if(table.slots.includes(item.slot))preferred++;}assert(preferred/2000>.72);assert(table.chance<.25);}for(const [type,t]of Object.entries(CHASE_DROPS)){assert(t.chance<.02);const rng=seeded(804),counts={};for(let i=0;i<20000;i++){const item=rollChaseItem({type},rng,18,i);if(item){counts[item.effect]=(counts[item.effect]||0)+1;assert(item.chase&&item.rarity==='legendary');assert(t.pool.includes(item.effect));}}const rate=Object.values(counts).reduce((a,b)=>a+b,0)/20000;assert(Math.abs(rate-t.chance)<.003);assert(!rollChaseItem({type},()=>0,1,1));}const rng=seeded(991);for(let i=0;i<2000;i++){const item=makeItem({rng,level:18,rarity:'legendary',slot:'weapon',uid:i});assert(!UNIQUE_ITEMS[item.effect]?.chase);}});
test('Expensive crown is a real one-off purchase, gated by funds and level; recipes cannot bypass rarity',()=>{const g=unlocked(),p=g.state.player,m=g.hubMerchants().find(m=>m.id==='outfitter');Object.assign(p,{x:m.x,y:m.y,level:16,scrap:8499});g.interact();const item=g.serviceStock().find(i=>i.effect==='horizonDiadem');assert.equal(item.price,8500);assert(!g.buyItem(item.uid));p.scrap++;assert(g.buyItem(item.uid));assert.equal(p.scrap,0);assert(g.equipItem(item.uid,'head'));assert(!g.buyItem(item.uid));const r=Engine.restore(g.serialize());assert(!r.state.world.shop.stock.some(i=>i.effect==='horizonDiadem'));r.retry();assert(!r.state.world.shop.stock.some(i=>i.effect==='horizonDiadem'));p.uniqueBlueprints=true;p.scrap=20000;for(const id of ['duneBeacon','glassMantle','slagHeart','horizonDiadem'])assert(!g.buyUniqueRecipe(id));});
test('Exceptional effects have meaningful bounded procs and preserve their appearance after reload',()=>{const g=shooting(),p=g.state.player,e=g.makeEnemy('slagcarrier',1050,640);p.equipment.weapon=makeUniqueItem('duneBeacon',18,1000);for(let i=0;i<4;i++)assert.equal(g.uniqueHit(e,100,'tide',false),100);assert.equal(g.uniqueHit(e,100,'tide',false),170);assert.equal(g.uniqueHit(e,100,'tide',true),100);assert.equal(g.uniqueHit(e,100,'tide',false),100);p.equipment.relic=makeUniqueItem('slagHeart',18,1001);assert.equal(g.uniqueHit(e,100,'ember',false),145);assert.equal(g.uniqueHit(e,100,'ember',false),100);p.equipment.suit=makeUniqueItem('glassMantle',18,1002);g.applyVenom();assert(g.useAntidote());assert.equal(p.ward,g.stats().maxHp*.15);assert(!g.useAntidote());assert.equal(Engine.restore(g.serialize()).state.player.equipment.suit.appearance,'filter');});
test('All original biome assets and exceptional item icons exist with aligned animation frames',()=>{for(const a of BIOME_AREAS)assert(fs.statSync(new URL('../assets/painted/'+a.file,import.meta.url)).size>10000);const atlas=JSON.parse(fs.readFileSync(new URL('../assets/expedition/enemies-biome-v81.json',import.meta.url)));assert.deepEqual(Object.keys(atlas),Object.keys(BIOME_ENEMIES));for(const s of Object.values(atlas)){assert.equal(s.frames.length,4);assert(s.bodyHeight>100);assert(s.frames.every(f=>f.anchor.join(',')===s.frames[0].anchor.join(',')));}for(const u of Object.values(UNIQUE_ITEMS).filter(u=>u.chase))assert(fs.statSync(new URL('../assets/items/'+u.art+'.webp',import.meta.url)).size>1000);});
console.log(`\n${n} biome, route, build and exceptional-loot checks passed.`);
