import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Engine,copy,canStand,seeded} from '../src/engine.js';
import {SPELLS,AREA_BY_ID,ENEMIES} from '../src/data.js';
import {spellProfile} from '../src/spell-variants.js';
import {companionMenu} from '../src/summons.js';
import {CREATURE_ENEMIES} from '../src/creature-content.js';
import {makeUniqueItem} from '../src/loot.js';
import {rollChaseItem} from '../src/chase-loot.js';
let n=0;const test=(name,fn)=>{fn();console.log('PASS '+name);n++;};
function arena(level=10,build=null){const g=new Engine('tide',482);g.state.player.level=level;g.state.player.preferredSpecialization=build;g.state.cores=[0,1,2,3];g.enterArea('ring');g.state.world.enemies=[];g.state.world.hazards=[];g.state.player.x=850;g.state.player.y=640;g.state.player.invincible=0;return g;}
function learn(g){g.state.player.skillPoints=1;assert(g.purchaseUpgrade({id:'summon',skill:true}));}
function equip(g,id){const item=makeUniqueItem(id,10,++g.idCounter);g.state.player.equipment[item.slot]=item;return item;}
test('Full minions unlock at 10; only Natuurhoeder gets one modest fox at 4',()=>{for(const build of [null,'hunter','elementalist']){const g=arena(4,build);g.state.player.skillPoints=1;assert(!g.purchaseUpgrade({id:'summon',skill:true}));assert(!g.upgradeChoices().some(c=>c.id==='summon'));assert(companionMenu(g.state.player).includes('VANAF NIVEAU 10'));}const g=arena(3,'builder');g.state.player.skillPoints=1;assert(!g.purchaseUpgrade({id:'summon',skill:true}));g.state.player.level=4;learn(g);assert(g.cast('summon'));assert.equal(g.state.summons.length,1);assert(g.state.summons[0].early);assert.equal(spellProfile(g.state.player,'summon').cost,26);assert(!g.selectCompanion('guardian'));g.state.player.menderUnlocked=true;assert(!g.selectCompanion('mender'));g.state.player.level=10;g.state.player.spellCd.summon=0;assert(g.cast('summon'));assert.equal(g.state.summons.length,2);assert(g.selectCompanion('guardian'));assert(g.selectCompanion('mender'));});
test('Ordinary level10 can learn, bind and cast summons on right click and number slots',()=>{const g=arena(),p=g.state.player;learn(g);g.assignRight('summon');g.assignSkill('summon',4);const mana=p.mana;assert(g.castRight());assert.equal(mana-p.mana,42);assert(!g.castSlot(4));p.spellCd.summon=0;assert(g.castSlot(4));assert.equal(g.state.summons.length,2);});
test('Animals survive time, die from damage and never automatically respawn',()=>{const g=arena();learn(g);g.cast('summon');for(let i=0;i<120;i++)g.updateCompanions(.25);assert.equal(g.state.summons.length,2);for(const u of g.state.summons)g.companionDamage(u,u.hp+1);g.updateCompanions(.01);assert.equal(g.state.summons.length,0);for(let i=0;i<30;i++)g.updateCompanions(1);assert.equal(g.state.summons.length,0);g.state.player.spellCd.summon=0;assert(g.cast('summon'));assert.equal(g.state.summons.length,2);});
test('Fox water bolts actually damage and wet targets without awarding direct-hit combo procs',()=>{const g=arena();learn(g);g.cast('summon');const e=g.makeEnemy('raider',1100,640,false,true);e.hp=e.maxHp=1000;g.state.world.enemies.push(e);for(let i=0;i<120;i++){g.updateCompanions(1/60);g.updateProjectiles(1/60);}assert(e.hp<1000);assert(e.wet>0);assert.equal(g.state.combos,0);});
test('Upgrades require workshop, learned animals, level and real funds; ranks persist',()=>{const g=new Engine(),p=g.state.player;p.level=10;p.skillPoints=1;learn(g);p.scrap=179;const workshop=g.hubMerchants().find(m=>m.id==='workshop');Object.assign(p,{x:workshop.x,y:workshop.y});g.interact();assert(!g.upgradeCompanion('scout','vitality'));p.scrap=2000;assert(g.upgradeCompanion('scout','vitality'));assert.equal(p.scrap,1820);assert(g.upgradeCompanion('scout','vitality'));assert(!g.upgradeCompanion('scout','vitality'));p.level=12;assert(g.upgradeCompanion('scout','vitality'));assert(!g.upgradeCompanion('scout','vitality'));assert(!g.upgradeCompanion('mender','potency'));assert.equal(Engine.restore(g.serialize()).state.player.companionUpgrades.scout.vitality,3);g.closeModal();g.enterArea('ring');g.state.world.enemies=[];g.cast('summon');assert(Math.abs(g.state.summons[0].maxHp-34*(1+Math.min(.65,g.stats().power))*1.45)<1e-6);});
test('Companions can be targeted, intercept shots, and are hurt by real enemy area attacks',()=>{const g=arena();learn(g);g.cast('summon');const u=g.state.summons[0],e=g.makeEnemy('stormtoad',u.x+150,u.y,false,true);e.attacks=2;const target=g.enemyTarget(e);assert(g.state.summons.some(a=>a.id===target.id));g.planAttack(e);assert.equal(e.windup.target.x,target.x);const hp=u.hp;g.state.world.threats.push({type:'bossPatch',x:u.x,y:u.y,r:80,damage:20,element:'fire',age:1,arm:.8,life:2,tick:0});g.updateBossTerrain(.1);assert.equal(u.hp,hp-20);});
test('Creature replacement is bounded and does not add enemies or overwrite bosses',()=>{for(let seed=1;seed<60;seed++){const g=arena();g.state.seed=seed;g.enterArea('glass');const w=g.state.world;assert.equal(w.enemies.filter(e=>e.faunaChanged).length,1);assert(w.enemies.filter(e=>e.creatureElite).length<=1);const count=w.enemies.length;g.addCreatureEncounter(w,AREA_BY_ID.glass);assert.equal(w.enemies.length,count);assert.equal(w.enemies.filter(e=>e.faunaChanged).length,1);assert(w.enemies.every(e=>canStand(e.x,e.y,e.radius,g.state.area)));}});
test('Creature patterns are distinct, aim locks once and the frog quick shot is still dodgeable',()=>{const g=arena();for(const type of Object.keys(CREATURE_ENEMIES)){const e=g.makeEnemy(type,1150,640,false,true);g.planAttack(e);assert.equal(e.windup.mode,{prismhorn:'antlerFan',mistprowler:'mistPounce',stormtoad:'stormSpit'}[type]);const target=copy(e.windup.target);g.state.player.y+=80;assert.deepEqual(e.windup.target,target);g.executeEnemyAttack(e);if(type==='mistprowler')assert(e.rush);else assert(g.state.projectiles.some(b=>b.source===e.id));}});
test('Stag reflection is frontal, bounded and can be bypassed with water or flanking',()=>{const g=arena(),e=g.makeEnemy('prismhorn',1100,640,true,true);e.creatureElite=true;e.angle=Math.PI;assert(Math.abs(g.creatureProtection(e,100,false)-55)<1e-9);assert.equal(g.state.projectiles.length,1);assert(g.state.projectiles[0].damage<=g.stats().maxHp*.04);assert(Math.abs(g.creatureProtection(e,100,false)-55)<1e-9);assert.equal(g.state.projectiles.length,1);e.wet=1;assert.equal(g.creatureProtection(e,100,false),100);e.wet=0;e.angle=0;assert.equal(g.creatureProtection(e,100,false),100);});
test('Elite panther has two visible relocations and elite frog death discharge gives time to escape',()=>{const g=arena(),e=g.makeEnemy('mistprowler',1100,640,true,true);e.creatureElite=true;e.hp=e.maxHp*.69;assert(g.updateCreatureEnemy(e,.01));assert(e.hidden&&e.mistStep);const spot=copy(e.mistStep);g.updateCreatureEnemy(e,.6);assert(!e.hidden);assert.equal(e.x,spot.x);e.hp=e.maxHp*.34;assert(g.updateCreatureEnemy(e,.01));g.updateCreatureEnemy(e,.6);assert(!g.updateCreatureEnemy(e,.01));const frog=g.makeEnemy('stormtoad',850,640,true,true);frog.creatureElite=true;g.creatureDeath(frog);const t=g.state.world.threats.at(-1),hp=g.state.player.hp;g.updateCreatureThreats(.1);assert.equal(g.state.player.hp,hp);t.age=t.arm;g.state.player.x+=250;g.updateCreatureThreats(.1);assert.equal(g.state.player.hp,hp);});
test('Optional chest requires consent, spawns three guards, pays once and cannot be replayed by reload',()=>{const g=arena(),w=g.state.world;w.ritual={x:850,y:640,status:'sealed',rewarded:false};const cash=g.state.player.scrap;assert.equal(w.enemies.length,0);assert(g.creatureInteraction());assert(g.startCreatureRitual());assert.equal(w.enemies.length,3);assert(!g.startCreatureRitual());assert(!g.creatureInteraction());for(const e of w.enemies)g.killEnemy(e);g.updateCreatureRitual();assert.equal(w.loot.filter(l=>l.item).length,1);assert(g.state.player.scrap>cash);const paid=g.state.player.scrap;g.updateCreatureRitual();assert.equal(g.state.player.scrap,paid);const r=Engine.restore(g.serialize());r.updateCreatureRitual();assert.equal(r.state.player.scrap,paid);assert(!r.startCreatureRitual());});
test('Regular loot stays reachable when an optional ritual is nearby',()=>{const g=arena(),w=g.state.world;w.sideDone=true;w.gate.eliteSpawned=true;w.ritual={x:850,y:640,status:'sealed'};w.loot.push({id:999,x:860,y:640,type:'loot',item:makeUniqueItem('command',10,1000)});assert.equal(g.interaction().type,'loot');assert(g.interact());assert.equal(g.state.player.inventory.length,1);assert.equal(w.ritual.status,'sealed');});
test('Meteor transforms one bomb with meaningful mana and cooldown tradeoffs',()=>{const g=arena(),p=g.state.player;p.learnedVariants=['ember:cluster'];p.spellVariants.ember='cluster';equip(g,'meteorStaff');const s=spellProfile(p,'ember');assert.equal(s.variant.fan,1);assert.equal(s.variant.blastRadius,175);assert(s.cost>=19);assert(s.interval>1);assert.equal(s.damage,51);assert(g.cast('ember',{x:1150,y:640}));assert.equal(g.state.projectiles.length,1);assert(g.state.projectiles[0].meteor);});
test('Spirit amber replaces even an upgraded three-fox pack; other companions keep their own role',()=>{const g=arena(),p=g.state.player;learn(g);p.specialization='builder';p.specializationTalents=['overclock','battery','squad'];equip(g,'spiritAmber');assert(g.cast('summon'));assert.equal(g.state.summons.length,1);assert(g.state.summons[0].spirit);assert.equal(spellProfile(p,'summon').cost,54);assert.equal(spellProfile(p,'summon').interval,22);g.selectCompanion('guardian');assert.equal(spellProfile(p,'summon').cost,42);p.spellCd.summon=0;assert(g.cast('summon'));assert(!g.state.summons[0].spirit);});
test('Creature-specific exceptional loot stays genuinely rare and never drops under level8',()=>{const rng=seeded(118);for(const type of Object.keys(CREATURE_ENEMIES)){let found=0;for(let i=0;i<10000;i++)if(rollChaseItem({type},rng,10,i))found++;assert(found>40&&found<150);assert(!rollChaseItem({type},()=>0,7,1));}});
test('All new sprites and icons are present and measured poses stay inside their real atlas',()=>{for(const name of ['companions-v82','creatures-v82']){const crops=JSON.parse(fs.readFileSync(new URL('../assets/expedition/'+name+'.json',import.meta.url)));assert.equal(Object.keys(crops).length,3);for(const spec of Object.values(crops))for(const f of spec.frames){const [x,y,w,h]=f.bounds;assert(x>=0&&y>=0&&x+w<=1536&&y+h<=1024);assert(f.anchor.every(a=>Number.isFinite(a)&&a>=0&&a<=1.1));}}for(const name of ['skill-summon-v82','companion-fox-v82','companion-boar-v82','companion-moth-v82','meteor-staff-v82','spirit-amber-v82'])assert(fs.statSync(new URL('../assets/items/'+name+'.webp',import.meta.url)).size>1000);});
console.log(`\n${n} creature, summon progression, death, training, encounter and legendary checks passed.`);
