import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {CoopSession,COOP_HP,COOP_DAMAGE,cleanInput} from '../src/coop-session.js';
import {Engine,distance,copy} from '../src/engine.js';
import {equipmentAppearance} from '../src/appearance.js';
import {createLanServer} from '../scripts/lan-server.mjs';
let n=0;async function test(name,fn){await fn();console.log('PASS '+name);n++;}
function party(){const s=new CoopSession(877);s.join({token:'mila',name:'Mila',build:'builder'});s.join({token:'raf',name:'Raf',build:'hunter'});s.ready('hero-1');s.ready('hero-2');return s;}
function travel(s,id){s.withActor(s.actors[0],()=>s.engine.enterArea(id));assert(s.travel);s.acceptTravel(s.actors[1].id);assert.equal(s.engine.state.area,id);}
function step(s,seconds){for(let i=0;i<seconds*60;i++)s.tick(1/60);}
await test('Two own builds, cameras, gear and sanitized names; a lobby waits for both',()=>{const s=new CoopSession(1),a=s.join({token:'a',name:'<Mila>',build:'builder'}),b=s.join({token:'b',name:'Raf',build:'hunter'});s.ready(a.id);assert(!s.started);s.ready(b.id);assert(s.started);assert.equal(a.player.name,'Mila');assert.notDeepEqual(equipmentAppearance(a.player),equipmentAppearance(b.player));assert.notEqual(a.player.equipment.weapon.uid,b.player.equipment.weapon.uid);const x=b.player.x;s.input(a.id,{x:1});s.tick(1/60);assert(a.player.x!==x);assert.equal(b.player.x,x);assert.throws(()=>s.join({token:'third'}));});
await test('Held numbered/controller skills are authoritative, bounded and keep ordinary cooldowns',()=>{
 assert.deepEqual(cleanInput({slots:[0,0,2,99,-1,'3']}).slots,[0,2]);const s=party();travel(s,'delta');const g=s.engine,a=s.actors[0];g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(a.player,{x:850,y:850});s.input(a.id,{slots:[0],aim:{x:1100,y:850}});s.tick(1/60);assert(g.state.projectiles.some(p=>p.ownerId===a.id));const mana=a.player.mana;s.tick(1/60);assert(a.player.mana>=mana);assert(a.player.spellCd.tide>0);
});
await test('Party travel needs both votes; encounter HP, damage and extra population scale once',()=>{const s=party();s.withActor(s.actors[0],()=>s.engine.enterArea('delta'));assert.equal(s.engine.state.area,'canal');s.acceptTravel('hero-2');assert.equal(s.engine.state.area,'delta');const solo=new Engine('tide',877);solo.enterArea('delta');const ordinary=s.engine.state.world.enemies.filter(e=>!e.partyExtra);assert.equal(ordinary.length,solo.state.world.enemies.length);for(let i=0;i<ordinary.length;i++){assert.equal(ordinary[i].maxHp,Math.round(solo.state.world.enemies[i].maxHp*COOP_HP));assert(Math.abs(ordinary[i].damageMultiplier/solo.state.world.enemies[i].damageMultiplier-COOP_DAMAGE)<.001);}assert(s.engine.state.world.enemies.some(e=>e.partyExtra));const hp=ordinary[0].maxHp;s.actors[0].player.level=9;s.actors[1].player.level=9;step(s,.1);assert.equal(ordinary[0].maxHp,hp);});
await test('Modal menus do not pause the other hero or provide poison immunity',()=>{const s=party();travel(s,'delta');s.engine.state.world.enemies=[];s.engine.state.world.hazards=[];const [a,b]=s.actors;a.mode='modal';a.pending={type:'upgrade',choices:[]};a.player.invincible=0;s.withActor(a,()=>s.engine.applyVenom(),true);const hp=a.player.hp,x=b.player.x;s.input(b.id,{x:1});step(s,.25);assert(b.player.x!==x);step(s,1);assert(a.player.hp<hp);assert.equal(a.mode,'modal');assert(Math.abs(s.engine.state.time-1.25)<.00001);});
await test('Player casts have ownership; kill XP is shared, drops are personal and cannot be stolen',()=>{const s=party();travel(s,'delta');const g=s.engine,[a,b]=s.actors;g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(a.player,{x:900,y:650});s.rpc(a.id,'castSlot',[0,{x:1150,y:650}]);assert(g.state.projectiles.some(p=>p.ownerId===a.id));const e=s.withActor(a,()=>g.makeEnemy('raider',1050,650));g.state.world.enemies.push(e);const ax=a.player.xp,bx=b.player.xp;s.withActor(a,()=>g.killEnemy(e));assert(a.player.xp>ax);assert.equal(a.player.xp-ax,b.player.xp-bx);const loot={id:++g.idCounter,x:b.player.x,y:b.player.y,type:'loot',ownerId:a.id,item:{uid:++g.idCounter,name:'Personal',slot:'weapon',rarity:'rare',stats:{}}};g.state.world.loot=[loot];assert(!s.snapshot(b.id).state.world.loot.length);assert(!s.withActor(b,()=>g.interaction()));s.withActor(a,()=>{Object.assign(a.player,{x:loot.x,y:loot.y});assert(g.interact());});assert.equal(a.player.inventory.at(-1).name,'Personal');assert(!b.player.inventory.length);});
await test('Boss lob, poison and persistent danger affect either hero while shared lifetimes advance once',()=>{const s=party();travel(s,'delta');const g=s.engine;g.state.world.enemies=[];g.state.world.hazards=[];g.state.world.threats=[];for(const a of s.actors)Object.assign(a.player,{x:950,y:650,invincible:0});g.state.projectiles=[{id:++g.idCounter,team:'enemy',type:'enemy-lob',x:950,y:650,origin:{x:950,y:650},end:{x:950,y:650},age:0,duration:.01,life:1,impactRadius:100,damage:10,radius:6,vx:0,vy:0,trail:[],element:'fire'}];const hp=s.actors.map(a=>a.player.hp);s.tick(1/60);assert(s.actors.every((a,i)=>a.player.hp<hp[i]));g.state.world.threats=[{id:9001,type:'bossPatch',x:950,y:650,r:100,element:'fire',damage:10,age:1,arm:.8,life:5,tick:0}];for(const a of s.actors)a.player.invincible=0;const before=s.actors.map(a=>a.player.hp);s.tick(1/60);assert(s.actors.every((a,i)=>a.player.hp<before[i]));assert(Math.abs(g.state.world.threats[0].life-(5-1/60))<.00001);});
await test('A fallen partner revives with a bandage and exposure; wipe retry restores both builds',()=>{const s=party();travel(s,'delta');s.engine.state.world.enemies=[];s.engine.state.world.hazards=[];const [a,b]=s.actors;Object.assign(a.player,{x:950,y:650});Object.assign(b.player,{x:1000,y:650,hp:0,downed:true});b.mode='downed';const stock=a.player.potions;assert(s.rpc(a.id,'interact'));step(s,2.1);assert(b.player.hp>0&&!b.player.downed);assert.equal(a.player.potions,stock-1);assert(a.player.healCooldown>7);assert(!s.rpc(a.id,'interact'));a.player.hp=b.player.hp=0;assert(s.retry());assert(s.actors.every(a=>a.player.hp>0));});
await test('A co-op timed trial waits for countdown, gives each hero one reward and restarts only after both agree',()=>{const s=party(),g=s.engine;g.state.completed=true;g.state.expansionCompleted=true;g.state.cores=[0,1,2,3];for(const a of s.actors){a.player.level=12;a.player.xp=0;a.player.hp=30;}s.rpc('hero-1','startChallenge',['trial-tide',1]);assert(s.travel);s.acceptTravel('hero-2');assert.equal(g.state.area,'trial-tide');assert.equal(s.snapshot('hero-1').state.mode,'playing');assert.equal(s.snapshot('hero-2').state.mode,'playing');assert(s.actors.every(a=>a.player.hp>30));assert.equal(g.state.world.trial.round,0);step(s,3.1);assert.equal(g.state.world.trial.round,1);for(let wave=1;wave<=4;wave++){for(const e of g.state.world.enemies.filter(e=>!e.dead))s.withActor(s.actors[0],()=>g.killEnemy(e));step(s,wave<4?3:.1);}assert(g.state.world.trial.done);assert(s.actors.every(a=>a.player.inventory.length===1));assert.notEqual(s.actors[0].player.inventory[0].uid,s.actors[1].player.inventory[0].uid);assert(s.actors.every(a=>a.pending?.type==='trialResult'));s.rpc('hero-1','restartChallenge');assert(g.state.world.trial.done);s.acceptTravel('hero-2');assert.equal(g.state.world.trial.round,0);assert(!g.state.world.trial.done);});
await test('Disconnect pauses combat; token reconnect and disk restore keep expedition state',()=>{const s=party();travel(s,'delta');const t=s.engine.state.time;s.leave('hero-2');step(s,1);assert.equal(s.engine.state.time,t);assert(s.snapshot('hero-1').state.coop.paused);assert.equal(s.join({token:'raf'}).id,'hero-2');step(s,.1);assert(s.engine.state.time>t);const saved=s.exportSave(),restored=new CoopSession();restored.restoreSave(saved);assert.equal(restored.engine.state.area,'delta');assert(restored.actors.every(a=>!a.connected));restored.join({token:'mila'});restored.join({token:'raf'});step(restored,.1);assert(restored.engine.state.time>s.engine.state.time);assert.deepEqual(restored.actors[0].player.equipment,s.actors[0].player.equipment);});
await test('Network inputs cannot teleport, invent damage or execute arbitrary engine methods',()=>{assert.deepEqual(cleanInput({x:Infinity,y:99,shoot:1,aim:{x:NaN,y:0},hp:999}),{x:0,y:1,shoot:false,right:false,paused:false,aim:null,slots:[]});const s=party(),p=s.actors[0].player;assert(!s.rpc('hero-1','killEnemy',[{}]));assert(!s.rpc('hero-1','makeEnemy',['boss']));assert(!s.rpc('hero-1','constructor',[]));assert(!s.rpc('hero-1','buyItem',[999999]));assert.equal(p.scrap,0);});
await test('Two real WebSocket clients join the local HTTP server and receive own authoritative movement',async()=>{const app=createLanServer({port:0,host:'127.0.0.1',persist:false}),address=await app.listening,base='http://127.0.0.1:'+address.port;assert((await (await fetch(base+'/lan/info')).json()).lan);assert.equal((await fetch(base+'/.lan-saves/last-expedition.json')).status,403);const sockets=[new WebSocket(base.replace('http','ws')+'/lan/ws'),new WebSocket(base.replace('http','ws')+'/lan/ws')],messages=[[],[]];try{await Promise.all(sockets.map((ws,i)=>new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;ws.onmessage=e=>messages[i].push(JSON.parse(e.data));})));for(const [i,ws]of sockets.entries()){ws.send(JSON.stringify({type:'join',name:['Mila','Raf'][i],build:['builder','hunter'][i]}));}await until(()=>messages.every(list=>list.some(m=>m.type==='joined')));for(const ws of sockets)ws.send(JSON.stringify({type:'ready'}));await until(()=>messages.every(list=>list.some(m=>m.state)));const before=messages.map(list=>list.findLast(m=>m.state).state.player.x);for(let i=0;i<12;i++){sockets[0].send(JSON.stringify({type:'input',input:{x:1,y:0}}));await new Promise(r=>setTimeout(r,30));}await until(()=>messages[0].findLast(m=>m.state).state.player.x>before[0]+10);assert.equal(messages[1].findLast(m=>m.state).state.player.x,before[1]);assert(messages[0].findLast(m=>m.state).state.coop.players[1].player.name==='Raf');}finally{for(const ws of sockets)ws.close();await app.close();}});
async function until(fn){const end=Date.now()+5000;while(!fn()){if(Date.now()>end)throw Error('Network condition timeout');await new Promise(r=>setTimeout(r,20));}}
await test('Server shutdown writes a complete checkpoint and a new process restores both private heroes',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'horizon-lan-save-')),savePath=join(dir,'party.json');let app;try{app=createLanServer({port:0,host:'127.0.0.1',savePath});await app.listening;app.session.join({token:'one',name:'Noordlicht'});app.session.join({token:'two',name:'Noordlicht'});app.session.ready('hero-1');app.session.ready('hero-2');assert.notEqual(app.session.actors[0].player.name,app.session.actors[1].player.name);app.session.actors[0].player.scrap=123;await app.close();const saved=JSON.parse(await readFile(savePath,'utf8'));assert(saved);app=createLanServer({port:0,host:'127.0.0.1',savePath});await app.listening;assert(app.session.started);assert.equal(app.session.actors[0].player.scrap,123);assert(app.session.actors.every(a=>!a.connected));}finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});
await test('Enemy bolts choose chest-height collision, rather than missing the partner nearest their feet',()=>{
 const s=party();travel(s,'delta');const g=s.engine,[a,b]=s.actors;g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(a.player,{x:1300,y:648,invincible:0});Object.assign(b.player,{x:1300,y:680,invincible:0});
 const hp=[a.player.hp,b.player.hp];g.state.projectiles=[{id:++g.idCounter,team:'enemy',type:'bolt',x:1290,y:660,vx:1200,vy:0,radius:4,damage:10,life:1,age:0,trail:[]}];s.tick(1/60);assert.equal(a.player.hp,hp[0]);assert(b.player.hp<hp[1]);assert.equal(g.state.projectiles.length,0);
});
await test('Victory reaches both heroes and remains visible; returning to a camp clears the result screen',()=>{
 const s=party();travel(s,'delta');s.engine.interaction=()=>({type:'win'});assert(s.rpc('hero-2','interact'));step(s,.2);assert(s.actors.every(a=>a.mode==='won'));assert(s.snapshot('hero-1').state.mode==='won');assert(s.snapshot('hero-2').state.mode==='won');
 assert(s.rpc('hero-1','enterArea',['skybridge']));s.acceptTravel('hero-2');assert(s.engine.state.expansionCompleted);assert.equal(s.snapshot('hero-1').state.mode,'playing');assert.equal(s.snapshot('hero-2').state.mode,'playing');
});
console.log(`\n${n} LAN authority, combat and network checks passed.`);
