import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Engine,canStand,clearLine,findPath,distance,copy} from '../src/engine.js';
import {STORY_ORDER} from '../src/story.js';
import {NATURE_AREAS,NATURE_ENEMIES,NATURE_LANDMARKS} from '../src/nature-content.js';
import {arenaObstacles,coverHit} from '../src/arena-layouts.js';
import {Renderer} from '../src/render.js';
import {updateHeroMotion} from '../src/hero-motion.js';
import {enemyPose} from '../src/enemy-motion.js';
import {updateEncounterThreat} from '../src/encounters.js';
let n=0;const test=(name,fn)=>{fn();console.log('PASS '+name);n++;};
function unlocked(id='lanternwood'){const g=new Engine('tide',683);g.state.cores=[0,1,2,3];g.state.storyPassed=STORY_ORDER.slice(0,22);g.state.natureVictories={crystalfalls:1};assert(g.enterArea(id));return g;}
function walk(g,target){const p=g.state.player,path=findPath(p,target,g.state.area,35);assert(path.length,'unreachable '+(target.to||target.id));for(const q of path){let frames=0;while(distance(p,q)>5&&frames++<1800){const a=Math.round(Math.atan2((q.y-p.y)/.78,q.x-p.x)/(Math.PI/4))*Math.PI/4;g.update(1/60,{x:Math.round(Math.cos(a)),y:Math.round(Math.sin(a))});}assert(frames<1800,'keyboard stalled '+JSON.stringify({target,q,position:{x:p.x,y:p.y}}));}assert(distance(p,target)<8);}
function clear(g){for(const e of g.state.world.enemies.filter(e=>!e.dead))g.killEnemy(e);g.state.player.xp=0;g.update(.01);}
function shooting(){const g=new Engine();g.enterArea('ring');g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(g.state.player,{x:850,y:640,invincible:0});return g;}
test('The forest city opens after chapter22; its separate boss requires a waterfall victory',()=>{const g=new Engine();assert(!g.enterArea('lanternwood'));g.state.cores=[0,1,2,3];g.state.storyPassed=STORY_ORDER.slice(0,21);assert(!g.isUnlocked('lanternwood'));g.state.storyPassed.push('heatworks');assert(g.enterArea('cooling-refuge'));const gate=g.state.world.portals.find(p=>p.to==='lanternwood');assert(!gate.locked);walk(g,gate);assert.equal(g.interaction().entity.to,'lanternwood');assert(g.interact());assert.equal(g.state.area,'lanternwood');assert(!g.isUnlocked('coppercrown'));const boss=g.state.world.portals.find(p=>p.to==='coppercrown');assert(boss.locked&&boss.reason.includes('Kristalwaterval'));assert.deepEqual(g.routeTo('crystalfalls'),['lanternwood','crystalfalls']);const events=g.takeEvents();assert(events.findIndex(e=>e.type==='natureregion')>events.findIndex(e=>e.type==='zone'));});
test('Every new city stall, dispersed gate, chest and side plaza accepts actual eight-direction walking',()=>{const g=unlocked();const targets=[...g.state.world.portals,...g.hubMerchants(),...g.state.world.loot,...NATURE_LANDMARKS];for(const point of targets){assert(canStand(point.x,point.y,35,'lanternwood'));walk(g,point);}assert.equal(g.state.natureDiscoveries.length,3);assert(g.state.world.portals.every((p,i,a)=>a.every((q,j)=>i===j||distance(p,q)>400)));const cash=g.state.player.scrap;for(const point of NATURE_LANDMARKS)walk(g,point);assert.equal(g.state.player.scrap,cash);g.enterArea('cooling-refuge');g.enterArea('lanternwood');assert.equal(g.state.natureDiscoveries.length,3);assert.equal(g.state.world.enemies.length,0);});
test('Waterfall has two groups and one exit; the crown has exactly one boss; both pay once per victory',()=>{const g=unlocked('crystalfalls'),w=g.state.world,p=g.state.player;g.state.natureVictories={};assert.equal(w.enemies.length,5);assert(!g.portalReady());assert.equal(w.portals.length,1);assert.equal(w.portals[0].to,'lanternwood');clear(g);assert.equal(w.nature.wave,2);assert.equal(w.enemies.filter(e=>!e.dead).length,6);assert(!g.portalReady());clear(g);assert(g.portalReady());assert(g.isUnlocked('coppercrown'));const cash=p.scrap;assert(!g.completeNatureArena());assert.equal(p.scrap,cash);assert.equal(g.state.natureVictories.crystalfalls,1);g.enterArea('lanternwood');g.enterArea('coppercrown');assert.deepEqual(g.state.world.enemies.map(e=>e.type),['crownbear']);clear(g);assert(g.portalReady());const paid=p.scrap;assert(!g.completeNatureArena());assert.equal(p.scrap,paid);g.enterArea('lanternwood');p.hp=51;p.mana=25;p.potions=1;p.antidotes=0;const chests=g.state.world.loot.length;g.enterArea('coppercrown');assert.equal(p.hp,51);assert.equal(p.mana,25);assert.equal(p.potions,1);assert.equal(p.antidotes,0);assert.equal(p.scrap,paid);assert.equal(g.state.world.enemies.length,1);g.enterArea('lanternwood');assert.equal(g.state.world.loot.length,chests);});
test('Both arena shapes have reachable spawns, drops and exits; painted islands block grounded shots',()=>{for(const id of ['crystalfalls','coppercrown']){const g=unlocked(id);for(let i=0;i<(id==='crystalfalls'?2:1);i++){for(const e of g.state.world.enemies.filter(e=>!e.dead)){assert(canStand(e.x,e.y,e.radius,id));assert(findPath(g.state.player,e,id,18).length);}clear(g);}for(const point of [...g.state.world.portals,...g.state.world.loot]){assert(canStand(point.x,point.y,22,id));assert(findPath(g.state.player,point,id,22).length);}for(const o of arenaObstacles(id)){assert(!canStand(o.x,o.y,18,id));assert(coverHit({x:o.x-o.rx-150,y:o.y},{x:o.x+o.rx+150,y:o.y},id));}g.state.world.enemies=[];walk(g,g.state.world.portals[0]);}});
test('Four new creatures have separate attacks, elements and painted release effects',()=>{const g=shooting();for(const type of Object.keys(NATURE_ENEMIES)){const e=g.makeEnemy(type,1100,640,false,true),modes=new Set();for(let i=0;i<(type==='crownbear'?3:2);i++){g.planAttack(e);modes.add(e.windup.mode);const effects=g.state.effects.length;g.executeEnemyAttack(e);assert(g.state.effects.length>effects);e.windup=null;}assert.equal(modes.size,type==='crownbear'?3:2);}});
test('Quick wind and fire shots lock aim and hit stationary targets while a sidestep escapes',()=>{for(const type of ['sunnewt','windowl']){function shot(dodge){const g=shooting(),e=g.makeEnemy(type,1150,640,false,true);g.planAttack(e);assert(e.windup.quick&&e.windup.total<=.35);Renderer.prototype.drawTelegraphs.call({ctx:{},drawV6Warning(){assert.fail('quick shot draws floor marker');}},{world:{enemies:[e]}});const target=copy(e.windup.target),hp=g.state.player.hp;if(dodge)g.state.player.y+=130;assert.deepEqual(e.windup.target,target);g.executeEnemyAttack(e);for(let i=0;i<90;i++)g.updateProjectiles(1/60);return hp-g.state.player.hp;}assert(shot(false)>0);assert.equal(shot(true),0);}});
test('Crown roots have three warned, bounded damaging fields; its ring also hurts living animals',()=>{const g=shooting(),e=g.makeEnemy('crownbear',1100,640,false,true);e.attacks=2;g.planAttack(e);assert.equal(e.windup.mode,'amberRoots');assert.equal(e.windup.targets.length,3);g.executeEnemyAttack(e);assert.equal(g.state.world.threats.filter(t=>t.type==='bossPatch'&&t.life>0).length,3);e.windup=null;e.attacks=2;g.planAttack(e);g.executeEnemyAttack(e);assert.equal(g.state.world.threats.filter(t=>t.type==='bossPatch'&&t.life>0).length,3);const t=g.state.world.threats.find(t=>t.life>0),p=g.state.player;Object.assign(p,{x:t.x,y:t.y,invincible:0});const hp=p.hp;t.age=1;g.updateBossTerrain(1);assert(p.hp<hp);e.windup=null;e.attacks=1;g.planAttack(e);g.executeEnemyAttack(e);const ring=g.state.world.threats.at(-1);g.state.summons=[{id:990,profile:'scout',x:ring.x+ring.r,y:ring.y,radius:17,hp:100,maxHp:100}];updateEncounterThreat(g,ring,.01);assert(g.state.summons[0].hp<100);const animalHp=g.state.summons[0].hp;updateEncounterThreat(g,ring,.01);assert.equal(g.state.summons[0].hp,animalHp);});
test('Boss speeds up once; save/restore freezes stats and checkpoint retry restores earned discoveries',()=>{const g=unlocked('coppercrown'),e=g.state.world.enemies[0];e.hp=e.maxHp*.49;const cd=e.cooldownMultiplier;g.updateNatureEnemy(e);assert.equal(e.phase,2);assert(e.cooldownMultiplier<cd);const next=e.cooldownMultiplier;g.updateNatureEnemy(e);assert.equal(e.cooldownMultiplier,next);g.state.player.level=25;const r=Engine.restore(g.serialize()).state.world.enemies[0];for(const key of ['hp','maxHp','damageMultiplier','cooldownMultiplier','phase'])assert.equal(r[key],e[key]);g.state.natureDiscoveries=['oldglass'];g.checkpoint();g.state.natureDiscoveries.push('canopy');g.state.natureVictories.coppercrown=8;g.retry();assert.deepEqual(g.state.natureDiscoveries,['oldglass']);assert(!g.state.natureVictories.coppercrown);});
test('Animals follow a cached detour around cover and remain on accessible ground',()=>{const g=shooting();g.enterArea('delta');g.state.world.enemies=[];g.state.world.hazards=[];const u={id:999,profile:'scout',x:700,y:640,radius:17},goal={x:1200,y:710};assert(!clearLine(u,goal,'delta',u.radius));const start=distance(u,goal);for(let i=0;i<420;i++){g.moveCompanionToward(u,goal,1/60);assert(canStand(u.x,u.y,u.radius,'delta'));}assert(distance(u,goal)<40);assert(distance(u,goal)<start*.1);});
test('Walking eases to idle without reversing the gait; charge and release transitions use bounded poses',()=>{const p={aim:{x:1,y:0},walkDistance:0};for(let i=0;i<30;i++)updateHeroMotion(p,3,0,1/60,180);const distanceBefore=p.walkDistance,blend=p.visualMotionBlend;updateHeroMotion(p,0,0,1/60,180);assert(p.visualMotionBlend>0&&p.visualMotionBlend<blend);assert.equal(p.walkDistance,distanceBefore);for(let i=0;i<60;i++)updateHeroMotion(p,0,0,1/60,180);assert(p.visualMotionBlend<.001);const wind=enemyPose({windup:{total:1,timer:.94}}),release=enemyPose({attackRelease:.06});assert.equal(wind.next,4);assert(wind.blend>.4&&wind.blend<.6);assert.equal(release.frame,5);assert.equal(release.next,0);assert(release.blend>.4&&release.blend<.6);});
test('Original environment and creature assets have valid measured ground anchors',()=>{for(const a of NATURE_AREAS)assert(fs.statSync(new URL('../assets/painted/'+a.file,import.meta.url)).size>10000);const atlas=JSON.parse(fs.readFileSync(new URL('../assets/expedition/nature-creatures-v83.json',import.meta.url)));assert.deepEqual(Object.keys(atlas),Object.keys(NATURE_ENEMIES));for(const s of Object.values(atlas)){assert.equal(s.frames.length,4);assert(s.bodyHeight>100);for(const f of s.frames){assert(f.bounds.every(Number.isFinite));assert(f.anchor.every(v=>v>=0&&v<=1.1));assert(f.bounds[0]+f.bounds[2]<=1254);assert(f.bounds[1]+f.bounds[3]<=1254);}}});
console.log(`\n${n} new region, navigation, creature attacks and movement checks passed.`);
