import assert from 'node:assert/strict';
import {Engine,copy} from '../src/engine.js';
import {SPELLS,AREA_BY_ID} from '../src/data.js';
import {makeItem} from '../src/loot.js';
import {SPELL_VARIANTS,spellProfile,variantKey} from '../src/spell-variants.js';
import {resistance,damageResistance} from '../src/resistances.js';
import {updateNewThreats} from '../src/enemy-variety.js';
import {BOUNTIES} from '../src/bounties.js';
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name);}const near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function arena(){const g=new Engine('tide',421);g.enterArea('ring');g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(g.state.player,{x:850,y:640,invincible:0,level:10,skillPoints:30,skills:Object.keys(SPELLS),mana:1000});return g;}
function trader(){const g=new Engine('tide',3),m=g.state.world.camp.services.find(m=>m.id==='workshop');Object.assign(g.state.player,{x:m.x,y:m.y,scrap:2000});return g;}
function item(g){const i=makeItem({rng:g.rng,rarity:'rare',slot:'suit',uid:++g.idCounter});g.state.player.inventory.push(i);return i;}
function dummy(g,x=1100,y=640){const e=g.makeEnemy('raider',x,y);Object.assign(e,{hp:10000,maxHp:10000,cd:99,stun:99});g.state.world.enemies.push(e);return e;}
test('Protected items reject atomic sales and recycling; markers survive restore and retry',()=>{const g=trader(),a=item(g),b=item(g),p=g.state.player;g.checkpoint();g.setItemMark(a.uid,'favorite');const cash=p.scrap;assert(!g.sellItems([a.uid,b.uid]));assert(!g.recycleItem(a.uid));assert.equal(p.scrap,cash);assert.equal(p.inventory.length,2);assert(!g.setItemMark(a.uid,'junk'));const h=Engine.restore(g.serialize());assert.equal(h.state.player.inventory[0].mark,'favorite');h.retry();assert.equal(h.state.player.inventory[0].mark,'favorite');assert(g.setItemMark(a.uid,''));assert(g.sellItems([a.uid,b.uid]));});
test('Marking does not advance the combat checkpoint; equipping clears sale designation',()=>{const g=arena(),i=item(g);g.checkpoint();const x=g.state.checkpoint.player.x;g.state.player.x+=20;g.setItemMark(i.uid,'junk');assert.equal(g.state.checkpoint.player.x,x);assert(g.equipItem(i.uid));assert.equal(g.state.player.equipment.suit.mark,'');});
test('Variant learning enforces base knowledge, levels and one point; switching preserves cooldown',()=>{const g=arena(),p=g.state.player;p.level=7;assert(!g.learnSpellVariant('tide','surf'));p.level=8;assert(g.learnSpellVariant('tide','surf'));assert.equal(p.skillPoints,29);assert(!g.learnSpellVariant('tide','surf'));assert(!g.learnSpellVariant('tide','lance'));p.spellCd.tide=.7;assert(g.selectSpellVariant('tide',''));assert.equal(p.spellCd.tide,.7);assert(g.selectSpellVariant('tide','surf'));assert.equal(p.spellCd.tide,.7);const h=Engine.restore(g.serialize());assert.equal(h.state.player.spellVariants.tide,'surf');assert.equal(h.state.player.learnedVariants.length,1);});
test('All 22 variants produce their advertised cast settings; returning to base restores original rules',()=>{for(const [spell,list] of Object.entries(SPELL_VARIANTS))for(const v of list){const g=arena(),p=g.state.player;assert.deepEqual(spellProfile(p,spell),SPELLS[spell]);assert(g.learnSpellVariant(spell,v.id));const profile=spellProfile(p,spell);assert(profile.cost>=SPELLS[spell].cost);assert(profile.interval>=SPELLS[spell].interval);assert(g.cast(spell,{x:1150,y:640}),variantKey(spell,v.id));if(SPELLS[spell].area){const f=g.state.fields[0];assert.equal(f.variant,v.id);near(f.damage,profile.damage*(1+g.stats().power+(g.stats()[SPELLS[spell].element]||0)));if(v.fieldSpeed===0)assert.equal(f.vx,0);if(v.targets)assert.equal(f.targetCount,v.targets);if(v.halfWidth)assert.equal(f.halfWidth,v.halfWidth);if(v.strikes)assert.equal(f.strikes.length,v.strikes);if(v.lineStrikes)assert.equal(f.strikes.length,3);}else if(spell!=='storm'){const b=g.state.projectiles[0];assert.equal(b.variant,v.id);assert.equal(g.state.projectiles.length,v.fan||1);if(v.pierce)assert.equal(b.pierce,v.pierce);if(v.bounces!==undefined)assert.equal(b.bounces,v.bounces);if(v.stationary)assert.equal(b.vx,0);if(v.returnAt)assert.equal(b.returnAt,v.returnAt);}assert(g.selectSpellVariant(spell,''));assert.deepEqual(spellProfile(p,spell),SPELLS[spell]);}});
test('A shared spell cooldown applies to left, right and numbered bindings after changing variants',()=>{const g=arena(),p=g.state.player;g.learnSpellVariant('tide','surf');g.assignRight('tide');g.assignSkill('tide',0);assert(g.cast());assert(!g.castRight());assert(!g.castSlot(0));g.selectSpellVariant('tide','');assert(!g.cast());});
test('Needle lightning hits two aligned targets; fork rays cannot multiply a single target hit',()=>{let g=arena();const a=dummy(g,1000),b=dummy(g,1130),c=dummy(g,1250);g.learnSpellVariant('storm','needle');g.cast('storm',{x:1400,y:640});assert(a.hp<10000&&b.hp<10000);assert.equal(c.hp,10000);g=arena();const e=dummy(g,900);g.state.player.stats.crit=-.07;g.learnSpellVariant('storm','fork');const damage=spellProfile(g.state.player,'storm').damage*(1+g.stats().power);g.cast('storm',{x:1100,y:640});near(10000-e.hp,damage);});
test('Flash bombs leave no fire while clustered bombs have weaker smaller fire fields',()=>{for(const id of ['flash','cluster']){const g=arena();g.learnSpellVariant('ember',id);g.cast('ember',{x:1100,y:640});for(let i=0;i<90;i++)g.updateProjectiles(1/60);const fire=g.state.world.hazards.filter(h=>h.type==='friendlyFire');assert.equal(fire.length,id==='flash'?0:3);if(id==='cluster')assert(fire.every(h=>h.r===48&&h.damage<7));}});
test('Glacier corridor and gate hit different footprints, and tempest chooses its target cap',()=>{for(const id of ['corridor','gate']){const g=arena();g.learnSpellVariant('glacier',id);g.cast('glacier',{x:1100,y:640});const along=dummy(g,1250,640),across=dummy(g,1100,770);g.updateFields(.01);if(id==='corridor'){assert(along.hp<10000);assert.equal(across.hp,10000);}else{assert.equal(along.hp,10000);assert(across.hp<10000);}}for(const [id,count]of [['focused',1],['drizzle',5]]){const g=arena();g.learnSpellVariant('tempest',id);for(let i=0;i<6;i++)dummy(g,1100+i*15);g.cast('tempest',{x:1100,y:640});g.updateFields(.01);assert.equal(g.state.world.enemies.filter(e=>e.hp<10000).length,count);}});
test('Resistance reduces poison exactly once; armor never cancels infection and cap prevents immunity',()=>{for(const [amount,expected]of [[0,.5],[.24,.38],[.6,.2],[2,.2]]){const g=arena(),p=g.state.player;p.stats.poisonResist=amount;p.stats.armor=.55;p.ward=500;p.wardTime=20;const hp=p.hp;assert(g.applyVenom());for(let i=0;i<480;i++)g.updateSurvival(1/60);near(p.hp,hp-g.stats().maxHp*expected);assert.equal(p.ward,500);assert.equal(p.venom,0);}near(resistance({poisonResist:5},'poisonResist'),.6);});
test('Element resistances protect only the matching damage type',()=>{const g=arena(),p=g.state.player;p.stats.fireResist=.24;p.stats.armor=0;g.hurtPlayer(20,'fire');near(p.hp,84.8);p.invincible=0;g.hurtPlayer(20,'electric');near(p.hp,64.8);assert.equal(damageResistance(g.stats(),'venom'),0);});
test('Spore clouds now infect with painful eight-second damage, not the old four HP poison',()=>{const g=arena(),p=g.state.player;g.state.world.hazards=[{type:'spore',x:p.x,y:p.y,r:60}];g.updateHazards(.01);assert.equal(p.venom,8);assert.equal(p.poison,0);g.state.world.hazards=[];for(let i=0;i<480;i++)g.updateSurvival(1/60);near(p.hp,50);});
test('Forge choices share a three-step budget, cost scrap and persist on the item',()=>{const g=trader(),p=g.state.player,i=p.equipment.suit;const hp=g.stats().maxHp,cash=p.scrap,cost=g.forgeCost(i);assert(g.reinforce('suit','poisonResist'));assert.equal(p.scrap,cash-cost);near(i.stats.poisonResist,.08);assert.equal(g.stats().maxHp,hp);assert(g.reinforce('suit','base'));assert.equal(g.stats().maxHp,hp+10);assert(g.reinforce('suit','fireResist'));assert.equal(i.enhance,3);const last=p.scrap;assert(!g.reinforce('suit','stormResist'));assert(!g.reinforce('suit','invalid'));assert.equal(p.scrap,last);const h=Engine.restore(g.serialize());near(h.state.player.equipment.suit.stats.poisonResist,.08);});
test('Resistance affixes occur across armor drops and remain bounded at high item levels',()=>{let found=0;const g=arena();for(let i=0;i<1000;i++){const item=makeItem({rng:g.rng,slot:'suit',rarity:'epic',level:30,uid:i});for(const [k,v]of Object.entries(item.stats))if(k.endsWith('Resist')){found++;assert(v<=.45);}}assert(found>300);});
test('Bounties unlock around chapters ten and fifteen and require a safe start',()=>{const g=new Engine('tide',1);assert(!g.startBounty('bounty-spore'));g.state.cores=[0,1];g.enterArea('forest');assert(g.isUnlocked('bounty-spore'));assert(!g.isUnlocked('bounty-solar'));assert(g.startBounty('bounty-spore'));assert(!g.startBounty('bounty-spore'));assert.equal(g.state.world.enemies.length,1);});
test('Spore boss mixes poison rings, roots, volleys and a locked venom jet',()=>{const g=arena(),e=g.makeEnemy('seedheart',1000,640);e.bountyBoss=true;g.state.world.enemies=[e];g.state.player.x=1150;const modes=[];for(let n=0;n<5;n++){g.planAttack(e);modes.push(e.windup.mode);g.executeEnemyAttack(e);}assert.deepEqual(modes,['tidalRing','seedVolley','roots','venomJet','seedVolley']);g.state.player.invincible=0;updateNewThreats(g,.34);assert(g.state.player.venom>0);assert(g.state.world.threats.some(t=>t.type==='ring'&&t.venom));});
test('Each bounty contains only its boss even after phase changes and hatch attacks',()=>{for(const id of Object.keys(BOUNTIES)){const g=new Engine('tide',8);g.state.completed=true;assert(g.startBounty(id));const e=g.state.world.enemies[0];assert(e.bountyBoss&&e.noReward);const ordinary=g.makeEnemy(e.type,e.x,e.y);assert(e.maxHp>ordinary.maxHp*1.7);e.hp=e.maxHp*.45;g.state.player.invincible=99;g.updateEnemies(.01);assert.equal(g.state.world.enemies.length,1);for(let n=0;n<6;n++){g.planAttack(e);g.executeEnemyAttack(e);}assert.equal(g.state.world.enemies.length,1);}});
test('Boss reward is paid once, never on failure; return and repeat do not grant free healing',()=>{for(const id of Object.keys(BOUNTIES)){const g=new Engine('tide',6);g.state.completed=true;g.state.player.hp=70;assert(g.startBounty(id));const p=g.state.player,w=g.state.world,initial=p.scrap;g.updateBounty();assert.equal(p.scrap,initial);g.killEnemy(w.enemies[0]);assert.equal(w.loot.length,0);g.updateBounty();assert.equal(p.scrap,initial+BOUNTIES[id].scrap);assert.equal(w.loot.length,1);assert(w.gate.open);const cash=p.scrap;g.updateBounty();assert.equal(p.scrap,cash);const h=Engine.restore(g.serialize());h.updateBounty();assert.equal(h.state.player.scrap,cash);h.enterArea(AREA_BY_ID[id].links[0]);assert.equal(h.state.player.hp,70);assert(h.startBounty(id,'scrap'));assert.equal(h.state.player.hp,70);assert(!h.state.world.enemies[0].dead);h.killEnemy(h.state.world.enemies[0]);h.updateBounty();assert.equal(h.state.player.scrap,cash+BOUNTIES[id].cash);}});
test('Repeated bounty rewards track the disclosed rarity odds and cash mode drops fewer items',()=>{for(const id of Object.keys(BOUNTIES)){let count=0,high=0,legend=0;const g=new Engine('tide',39);g.state.completed=true;for(let i=0;i<1500;i++){g.enterArea('canal');g.startBounty(id,i<750?'loot':'scrap');g.killEnemy(g.state.world.enemies[0]);g.updateBounty();const loot=g.state.world.loot;if(i<750){assert.equal(loot.length,1);high+=['rare','epic','legendary'].includes(loot[0].item.rarity);legend+=loot[0].item.rarity==='legendary';}else count+=loot.length;}assert(count>130&&count<240);assert(high>250&&high<650);assert(legend<50);}});
test('Trials lock variants and forge choices alongside the existing build lock',()=>{const g=arena();g.learnSpellVariant('tide','surf');g.state.completed=true;g.enterArea('skybridge');assert(g.startChallenge('trial-tide'));assert(!g.selectSpellVariant('tide',''));assert(!g.learnSpellVariant('tide','lance'));assert(!g.setItemMark(g.state.player.equipment.suit.uid,'favorite'));assert(!g.reinforce('suit','poisonResist'));});
console.log(`\n${n} progression, resistance and bounty checks passed.`);
