import assert from 'node:assert/strict';
import {Engine,canStand,findPath,distance,copy} from '../src/engine.js';
import {SPELLS,ENEMIES} from '../src/data.js';
import {makeUniqueItem,makeItem} from '../src/loot.js';
import {UNIQUE_ITEMS} from '../src/unique-items.js';
import {V6_ENEMIES} from '../src/v6-enemies.js';
import {CITY_NPCS,CITY_LANDMARKS,CONTRACT_NPCS} from '../src/city.js';
import {BOUNTIES} from '../src/bounties.js';
import {normalizeSettings} from '../src/settings.js';
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
function arena(){const g=new Engine('tide',84);g.enterArea('ring');g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(g.state.player,{x:850,y:640,invincible:0,level:10});g.state.player.stats.crit=-.07;return g;}
function equip(g,id){const u=makeUniqueItem(id,8,++g.idCounter);u.stats={};g.state.player.equipment[u.slot]=u;return u;}
function dummy(g,type='raider',x=1150,y=640){const e=g.makeEnemy(type,x,y,false,true);e.hp=e.maxHp=10000;e.cd=99;g.state.world.enemies.push(e);return e;}
test('Dieren kosten mana, delen cooldown, vervangen de groep en blijven tot ze vallen',()=>{const g=arena(),p=g.state.player;p.skills.push('summon');p.hotbar[3]='summon';p.rightAbility='summon';const mana=p.mana;assert(g.castSlot(3));assert.equal(p.mana,mana-SPELLS.summon.cost);assert.equal(g.state.summons.length,2);assert(!g.castRight());const first=g.state.summons.map(u=>u.id);p.spellCd.summon=0;g.castRight();assert(g.state.summons.every(u=>!first.includes(u.id)));g.updateCompanions(19);assert.equal(g.state.summons.length,2);for(const u of g.state.summons)g.companionDamage(u,10000);g.updateCompanions(.01);assert.equal(g.state.summons.length,0);g.enterArea('canal');assert(!g.cast('summon'));});
test('Een echte waterlichtbout raakt een doel; T wijzigt doel zonder een nieuwe groep of gratis mana',()=>{const g=arena(),p=g.state.player;p.skills.push('summon');g.cast('summon');const a=dummy(g,'raider',1100,430),b=dummy(g,'raider',1300,740),mana=p.mana,ids=g.state.summons.map(u=>u.id);assert(g.commandCompanions(b));assert.equal(p.summonTarget,b.id);assert.equal(p.mana,mana);assert.deepEqual(g.state.summons.map(u=>u.id),ids);for(let i=0;i<120;i++){g.updateCompanions(1/60);g.updateProjectiles(1/60);}assert(b.hp<10000);assert.equal(a.hp,10000);assert.equal(p.summonTarget,b.id);});
test('Moszwijn onderschept ook snelle projectielen; lichtmot geeft maximaal 24 leven',()=>{let g=arena(),p=g.state.player;p.skills.push('summon');g.selectCompanion('guardian');g.cast('summon');const u=g.state.summons[0];Object.assign(u,{x:1000,y:640});const hp=p.hp,botHp=u.hp;g.state.projectiles=[{team:'enemy',type:'precision',x:1150,y:620,vx:-1600,vy:0,damage:18,radius:7,life:1,age:0,trail:[]}];g.updateProjectiles(.3);assert.equal(p.hp,hp);assert.equal(u.hp,botHp-18);assert.equal(g.state.projectiles.length,0);g=arena();p=g.state.player;p.skills.push('summon');assert(!g.selectCompanion('mender'));p.menderUnlocked=true;g.selectCompanion('mender');g.cast('summon');p.hp=20;for(let i=0;i<950;i++)g.updateCompanions(1/60);assert(p.hp<=44);assert(p.hp>20);});
test('Alle nieuwe vijanden hebben verschillende echte patronen; waarschuwingen volgen geen bewegend doel',()=>{for(const type of V6_ENEMIES){const g=arena(),e=dummy(g,type),seen=new Set();for(let i=0;i<(ENEMIES[type].boss?3:2);i++){g.planAttack(e);seen.add(e.windup.mode);const target=copy(e.windup.target);g.state.player.x+=25;assert.deepEqual(e.windup.target,target);g.executeEnemyAttack(e);e.windup=null;}assert.equal(seen.size,ENEMIES[type].boss?3:2,type);assert(g.takeEvents().some(e=>e.type==='enemyattack'));}});
test('Bastion beschermt een buur; natmaken schakelt de bescherming uit en reparaties zijn begrensd',()=>{const g=arena(),shield=dummy(g,'bulwark',1100,640),target=dummy(g,'sniper',1180,660);shield.angle=Math.PI;g.updateV6Enemy(shield);g.hitEnemy(target,100,'physical',true);assert.equal(target.hp,9928);shield.wet=2;g.updateV6Enemy(shield);g.hitEnemy(target,100,'physical',true);assert.equal(target.hp,9828);const drone=dummy(g,'repairer',1120,700);for(let i=0;i<4;i++){g.planAttack(drone);drone.windup.mode='repairPulse';g.executeEnemyAttack(drone);drone.windup=null;target.hp-=500;}assert.equal(target.repairs,3);});
test('Gifbanen raken pas na de waarschuwing; één infectie kost 50% leven en stapelt niet',()=>{const g=arena(),p=g.state.player,e=dummy(g,'tideleviathan');g.planAttack(e);g.executeEnemyAttack(e);const t=g.state.world.threats.find(t=>t.type==='v6lane');Object.assign(p,{x:t.x,y:t.y});const hp=p.hp;g.updateV6Threats(.1);assert.equal(p.hp,hp);t.age=t.arm;g.updateV6Threats(.1);assert(p.venom>0);assert.equal(p.venomDamage,g.stats().maxHp*.5/8);p.invincible=0;g.updateV6Threats(1);assert.equal(p.venomDamage,g.stats().maxHp*.5/8);assert(p.hp>0);});
test('Waterlenzen ontladen eenmaal, begrensd tot drie; condensator verbruikt zijn lading',()=>{let g=arena(),e=dummy(g);equip(g,'waterlens');for(let i=0;i<5;i++){g.state.player.effectCooldowns.waterlens=0;g.hitEnemy(e,1,'tide');}assert(g.state.world.threats.filter(t=>t.type==='waterlens'&&t.life>0).length<=3);const hp=e.hp;g.hitEnemy(e,10,'storm');assert(e.hp<hp-10);assert(g.state.world.threats.filter(t=>t.type==='waterlens').every(t=>t.life===0));g=arena();e=dummy(g);equip(g,'capacitor');for(let i=0;i<3;i++)g.hitEnemy(e,1,'tide');e.wet=0;const health=e.hp;g.hitEnemy(e,100,'storm');assert.equal(health-e.hp,135);assert.equal(g.state.player.capacitorCharge,0);});
test('Alle acht unieke stukken bewaren eigen artwork en effect na save; dure recepten zijn eenmalig',()=>{const g=arena();for(const id of Object.keys(UNIQUE_ITEMS)){const i=makeUniqueItem(id,8,++g.idCounter);assert(i.text.includes(UNIQUE_ITEMS[id].text));g.state.player.inventory.push(i);}const restored=Engine.restore(g.serialize());assert.deepEqual(restored.state.player.inventory.map(i=>i.effect),Object.keys(UNIQUE_ITEMS));g.state.cores=[0];g.enterArea('highway');const p=g.state.player;p.level=8;p.scrap=2400;p.uniqueBlueprints=true;const shop=g.hubMerchants().find(m=>m.id==='workshop');Object.assign(p,shop);assert(g.buyUniqueRecipe('command'));assert.equal(p.scrap,1200);assert(!g.buyUniqueRecipe('command'));assert(!g.buyUniqueRecipe('missing'));});
test('Stadsquests vereisen echte ontdekkingen en terugbrengen; beloningen worden één keer betaald',()=>{const g=new Engine();g.state.cores=[0];g.enterArea('highway');const p=g.state.player;Object.assign(p,CITY_NPCS.find(n=>n.id==='milo'));assert(g.acceptCityQuest('milo'));assert(!g.claimCityQuest('milo'));for(const l of CITY_LANDMARKS){Object.assign(p,l);g.updateCityQuests();}assert.equal(g.cityQuest('milo').status,'ready');assert(!g.claimCityQuest('milo'));Object.assign(p,CITY_NPCS.find(n=>n.id==='milo'));const money=p.scrap;assert(g.claimCityQuest('milo'));assert.equal(p.scrap,money+100);assert(!g.claimCityQuest('milo'));Object.assign(p,CITY_NPCS.find(n=>n.id==='ilya'));g.acceptCityQuest('ilya');g.enterArea('workshop-v6');g.state.world.sideDone=true;g.updateCityQuests();const loot=g.state.world.loot.find(l=>l.quest==='ilya');assert(loot);assert(g.collectCityRecovery(loot));assert(!g.collectCityRecovery(loot));g.enterArea('highway');Object.assign(p,CITY_NPCS.find(n=>n.id==='ilya'));assert(g.claimCityQuest('ilya'));assert(p.menderUnlocked);const r=Engine.restore(g.serialize());r.retry();assert.equal(r.cityQuest('ilya').status,'completed');});
test('Baascontracten staan bereikbaar in de wereld en kondigen zich eenmaal aan',()=>{const g=new Engine();g.state.completed=true;for(const [area,n]of Object.entries(CONTRACT_NPCS)){g.enterArea(area);assert(canStand(n.x,n.y,35,area));assert(findPath(g.state.player,n,area,35).length);Object.assign(g.state.player,n);assert.equal(g.interaction().entity.id,n.id);assert(g.interact());assert.equal(g.state.pending.type,'quest');g.closeModal();g.takeEvents();g.update(.01);assert.equal(g.takeEvents().filter(e=>e.type==='contractunlocked').length,1);g.update(.01);assert(!g.takeEvents().some(e=>e.type==='contractunlocked'));}});
test('Overdruk verhoogt risico en beloning; gerichte slotkeuze en één betaling blijven gelden',()=>{const g=new Engine();g.state.completed=true;const p=g.state.player,initialHp=p.hp;g.startBounty('bounty-spore','loot',true,'boots');assert.equal(p.hp,initialHp);const boss=g.state.world.enemies[0];assert.equal(boss.type,'tideleviathan');const actual=boss.maxHp;g.killEnemy(boss);const cash=p.scrap;g.updateBounty();assert.equal(p.scrap-cash,78);assert.equal(g.state.world.loot[0].item.slot,'boots');assert(!g.updateBounty());assert.equal(g.state.bountyVictories['bounty-spore'],1);g.enterArea('forest');g.startBounty('bounty-spore','loot',false);assert(g.state.world.enemies[0].maxHp<actual);});
test('Nieuwe instellingen begrenzen volumes en behouden veilige defaults bij ongeldige invoer',()=>{assert.deepEqual(normalizeSettings({music:-2,effects:3,quality:'invalid',cursor:99}),{music:0,effects:1,shake:.6,quality:'auto',cursor:1,questCollapsed:false});});

test('Zonneoven raakt ook het primaire doel, heeft vijf seconden cooldown en procs herhalen zichzelf niet',()=>{const g=arena(),e=dummy(g),near=dummy(g,'raider',1180,650);equip(g,'furnace');for(let i=0;i<3;i++)g.hitEnemy(e,1,'ember');assert.equal(e.hp,9977);assert.equal(near.hp,9980);assert.equal(g.state.player.effectCooldowns.furnace,5);for(let i=0;i<3;i++)g.hitEnemy(e,1,'ember');assert.equal(near.hp,9980);});
test('Roedelhoeder versterkt waterlicht en herstelt levende dieren zonder dode dieren te herleven',()=>{const g=arena(),p=g.state.player;p.skills.push('summon');equip(g,'command');g.selectCompanion('scout');g.cast('summon');const e=dummy(g),u=g.state.summons[0];g.commandCompanions(e);u.hp-=10;const hp=u.hp;g.hitEnemy(e,1,'tide');assert.equal(u.hp,hp+4);g.hitEnemy(e,1,'tide');assert.equal(u.hp,hp+4);g.updateCompanions(.6);const bolt=g.state.projectiles.find(b=>b.companion);assert(bolt);assert(Math.abs(bolt.damage-8*(1+Math.min(.65,g.stats().power))*1.22)<1e-8);u.hp=0;p.effectCooldowns.command=0;g.hitEnemy(e,1,'tide');assert.equal(u.hp,0);});
test('Antidotumschild houdt directe schade tegen maar geen gifschade; schrootgordel heeft een cooldown',()=>{let g=arena(),p=g.state.player;equip(g,'filter');assert(g.applyVenom());assert(g.useAntidote());assert.equal(p.ward,24);assert.equal(p.wardTime,6);assert.equal(p.antidoteCooldown,30);const hp=p.hp;g.hurtPlayer(10,'physical');assert.equal(p.hp,hp);const shield=p.ward;p.venom=8;p.venomTick=0;p.venomDamage=6.25;g.updateSurvival(1);assert.equal(p.hp,hp-6.25);assert.equal(p.ward,shield);assert(!g.useAntidote());g=arena();p=g.state.player;equip(g,'magnet');p.mana=20;p.spellCd.summon=10;const a=dummy(g),b=dummy(g);a.noReward=b.noReward=true;g.killEnemy(a);assert.equal(p.mana,25);assert.equal(p.spellCd.summon,9);g.killEnemy(b);assert.equal(p.mana,25);assert.equal(p.spellCd.summon,9);});
test('Getijdenstappers vertragen gewone vijanden; kristal telt alleen echte bevriezing en verlies betaalt niet',()=>{let g=arena(),p=g.state.player;equip(g,'tidestep');const e=dummy(g,'raider',900,640),boss=dummy(g,'tideleviathan',920,640);g.dash(1,0);assert.equal(e.slow,2);assert(!(boss.slow>0));assert.equal(g.state.world.threats.filter(t=>t.type==='waterlens'&&t.life>0).length,1);g=arena();equip(g,'crystal');const frozen=dummy(g);frozen.hp=1;frozen.wet=1;g.hitEnemy(frozen,2,'frost');assert.equal(g.state.projectiles.filter(b=>b.uniqueSecondary).length,2);const stunned=dummy(g);stunned.hp=1;stunned.stun=.5;g.state.player.effectCooldowns.crystal=0;g.hitEnemy(stunned,2,'physical');assert.equal(g.state.projectiles.length,2);g=new Engine();g.state.completed=true;g.startBounty('bounty-spore');const cash=g.state.player.scrap;g.killEnemy(g.state.world.enemies[0]);g.state.mode='dead';assert(!g.updateBounty());assert.equal(g.state.player.scrap,cash);assert(!g.state.world.bounty.paid);});
console.log(`\n${passed} v6 companion, enemy, unique, quest and contract checks passed.`);
