import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Engine,canStand,findPath,distance,copy} from '../src/engine.js';
import {STORY_ORDER} from '../src/story.js';
import {V8_AREAS,V8_ENEMIES} from '../src/v8-content.js';
import {makeItem,dropProfile,DROP_TABLES} from '../src/loot.js';
import {equipmentAppearance} from '../src/appearance.js';
import {scaleEnemy} from '../src/balance.js';
import {Renderer} from '../src/render.js';
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
function unlocked(id){const g=new Engine('tide',681);g.state.completed=true;g.state.cores=[0,1,2,3];g.state.storyPassed=STORY_ORDER.slice(0,STORY_ORDER.indexOf(id));assert(g.enterArea(id));return g;}
function clear(g){for(const e of g.state.world.enemies.filter(e=>!e.dead))g.killEnemy(e);g.state.player.xp=0;g.update(.01);}
function walk(g,target){const p=g.state.player,path=findPath(p,target,g.state.area,35);assert(path.length,g.state.area+' unreachable '+(target.to||target.id));for(const q of path){let frames=0;while(distance(p,q)>5&&frames++<1600){const a=Math.round(Math.atan2((q.y-p.y)/.78,q.x-p.x)/(Math.PI/4))*Math.PI/4;g.update(1/60,{x:Math.round(Math.cos(a)),y:Math.round(Math.sin(a))});}assert(frames<1600,g.state.area+' stalled '+(target.to||target.id));}assert(distance(p,target)<8);}
test('Act V and VI unlock sequentially; Aurelia progress never skips the new bosses',()=>{const g=new Engine();assert.equal(STORY_ORDER.length,24);assert(!g.isUnlocked('metro-refuge'));g.state.completed=true;g.state.cores=[0,1,2,3];assert(g.isUnlocked('metro-refuge'));assert(!g.isUnlocked('deepwater'));assert(!g.enterArea('tower'));for(const a of V8_AREAS){g.state.storyPassed=STORY_ORDER.slice(0,STORY_ORDER.indexOf(a.id));assert(g.isUnlocked(a.id));assert(g.enterArea(a.id));assert.equal(g.state.area,a.id);if(!a.safe)assert(!g.canSelectDestination(STORY_ORDER[STORY_ORDER.indexOf(a.id)+1]||'invalid'));}});
test('Every new hub gate, merchant and chest is reachable by actual keyboard walking',()=>{for(const id of ['metro-refuge','cooling-refuge']){const g=unlocked(id);assert(g.state.world.safeHub);assert.equal(g.state.world.enemies.length,0);const targets=[...g.state.world.portals,...g.hubMerchants(),...g.state.world.loot];for(const target of targets){assert(canStand(target.x,target.y,35,id),id+' small landing '+(target.to||target.id));walk(g,target);}}});
test('The four ordinary arenas require both waves and pay the completion reward once',()=>{for(const a of V8_AREAS.filter(a=>!a.safe&&!a.bossArena)){const g=unlocked(a.id),w=g.state.world;assert(!g.portalReady());assert.equal(w.portals.length,1);clear(g);assert.equal(w.sideRound,2);assert(!g.portalReady());assert(w.enemies.some(e=>!e.dead&&e.guardian));clear(g);assert(g.portalReady());assert(w.sideDone);assert.equal(w.loot.filter(l=>l.expeditionReward).length,1);const cash=g.state.player.scrap;g.completeV8Arena();assert.equal(g.state.player.scrap,cash);for(const point of [w.gate,...w.loot])assert(findPath(g.state.player,point,a.id,24).length);g.enterArea(a.links[0]);g.enterArea(a.id);assert.equal(g.state.player.scrap,cash);assert(g.arenaCleared());}});
test('New bosses have one opponent, three recognisable attacks and a second phase without adds',()=>{for(const id of ['deepwater','tower']){const g=unlocked(id),e=g.state.world.enemies[0];assert.equal(g.state.world.enemies.length,1);const modes=new Set();for(let i=0;i<3;i++){g.planAttack(e);assert(e.windup.total>=1);assert(!e.windup.quick);modes.add(e.windup.mode);g.executeEnemyAttack(e);e.windup=null;}assert.equal(modes.size,3);e.hp=e.maxHp*.49;g.updateV6Enemy(e);assert.equal(e.phase,2);assert.equal(g.state.world.enemies.length,1);assert.equal(dropProfile(e),'boss');assert.equal(DROP_TABLES.boss.chance,1);}});
test('The final victory waits for connecting the regulator after defeating the tower boss',()=>{const g=unlocked('tower');clear(g);assert.equal(g.state.mode,'playing');assert(!g.state.world.coreCollected);Object.assign(g.state.player,g.state.world.gate);assert(g.interact());assert.equal(g.state.mode,'won');assert(g.state.expansionCompleted);});
test('Encounter pressure rises chapter by chapter and remains frozen through equipment and save changes',()=>{let hp=0,damage=0,cooldown=2;for(const a of V8_AREAS.filter(a=>!a.safe)){const g=unlocked(a.id),e=g.makeEnemy('pressurediver',950,650);assert(e.maxHp>hp);assert(e.damageMultiplier>damage||a.stage===0);assert(e.cooldownMultiplier<cooldown);hp=e.maxHp;damage=e.damageMultiplier;cooldown=e.cooldownMultiplier;e.hp*=.4;g.state.world.enemies=[e];g.state.player.level=25;scaleEnemy(e,5,25);const expected=copy(e),restored=Engine.restore(g.serialize()).state.world.enemies[0];for(const key of ['hp','maxHp','damageMultiplier','cooldownMultiplier','level'])assert.equal(restored[key],expected[key],a.id+' '+key);}});
test('Head gear swaps manually, protects against poison, accepts upgrades and survives reload',()=>{const g=new Engine(),p=g.state.player;assert(p.equipment.head.empty);const helmet=makeItem({rng:g.rng,baseId:'filter-hood',slot:'head',rarity:'rare',level:1,uid:++g.idCounter});p.inventory.push(helmet);assert(g.equipItem(helmet.uid,'head'));assert.equal(p.equipment.head.uid,helmet.uid);const workshop=g.hubMerchants().find(m=>m.id==='workshop');Object.assign(p,{x:workshop.x,y:workshop.y,scrap:1000});assert(g.reinforce('head','poisonResist'));assert(g.stats().poisonResist>=.08);assert(g.reinforce('head','base'));assert.equal(p.equipment.head.enhance,2);assert.equal(Object.keys(p.equipment).length,8);assert.equal(Engine.restore(g.serialize()).state.player.equipment.head.uid,helmet.uid);});
test('Late shops provide usable arrival gear, superior saving targets and an actual head selection',()=>{let power=0;for(const [id,level]of [['metro-refuge',12],['cooling-refuge',14]]){const g=unlocked(id),p=g.state.player;p.level=level;const stock=g.state.world.shop.stock;assert(stock.some(i=>i.slot==='head'));assert(stock.slice(0,6).every(i=>i.requiredLevel<=level));const focus=stock.find(i=>i.investment&&i.slot==='weapon');assert(focus.price>=2000);assert(focus.stats.power>power);power=focus.stats.power;const service=g.hubMerchants().find(m=>m.id==='outfitter');Object.assign(p,{x:service.x,y:service.y,scrap:5000});g.interact();const helmet=g.serviceStock().find(i=>i.slot==='head'&&i.requiredLevel<=level);assert(helmet);assert(g.buyItem(helmet.uid));assert(p.equipment.head.empty);assert(g.equipItem(helmet.uid,'head'));}});
test('Equipped armor, focus and helmet drive the same eight-direction appearance selection',()=>{const p=new Engine().state.player;for(const style of ['light','heavy','filter','storm'])for(const focus of ['tidal','solar','storm','crystal']){p.equipment.suit.appearance=style;p.equipment.weapon.appearance=focus;p.equipment.head={appearance:style==='light'?'field':style};const a=equipmentAppearance(p);assert.equal(a.armor,style);assert.equal(a.focus,focus);assert.equal(a.helmet,style==='light'?'field':style);const key=a.key;p.equipment.weapon.rarity='legendary';assert(equipmentAppearance(p).legendary);if(!a.legendary)assert.notEqual(equipmentAppearance(p).key,key);p.equipment.weapon.rarity='common';}const rigs=JSON.parse(fs.readFileSync(new URL('../assets/painted/hero-gear-v8.json',import.meta.url)));for(const frames of Object.values(rigs.styles)){assert.equal(frames.length,5);for(const f of frames){assert(f.grip);assert(f.head);assert(f.leg);}}});
test('Fast drone fire has no ground marker, locks aim, travels visibly and can be dodged',()=>{function shot(dodge){const g=new Engine();g.enterArea('ring');g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(g.state.player,{x:850,y:640,invincible:0});const e=g.makeEnemy('rimedrone',1150,640,false,true);g.planAttack(e);assert(e.windup.quick&&e.windup.total<=.35);const target=copy(e.windup.target),hp=g.state.player.hp;const fake={ctx:{},drawV6Warning(){throw Error('fast attack draws floor warning');}};Renderer.prototype.drawTelegraphs.call(fake,{world:{enemies:[e]}});if(dodge)g.state.player.y+=130;assert.deepEqual(e.windup.target,target);g.executeEnemyAttack(e);assert.equal(g.state.player.hp,hp);assert(g.state.effects.some(f=>f.type==='weapon-flash'));assert.equal(g.state.projectiles.length,1);for(let i=0;i<90;i++)g.updateProjectiles(1/60);return hp-g.state.player.hp;}assert(shot(false)>0);assert.equal(shot(true),0);});
test('Flankers move laterally, ease direction changes and obey collision when finding a path',()=>{const g=new Engine();g.enterArea('delta');g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(g.state.player,{x:1140,y:710});const e=g.makeEnemy('hunter',700,630,false,true);e.cd=99;g.state.world.enemies=[e];const start=distance(e,g.state.player),y=e.y;for(let i=0;i<360;i++){g.updateEnemies(1/60);assert(canStand(e.x,e.y,e.radius,g.state.area));}assert(distance(e,g.state.player)<start);assert(Math.abs(e.y-y)>35);assert(Number.isFinite(e.steerX)&&Number.isFinite(e.steerY));});
test('All new item icons, environment files and enemy atlases are present and nonempty',()=>{for(const a of V8_AREAS)assert(fs.statSync(new URL('../assets/painted/'+a.file,import.meta.url)).size>10000);for(const name of ['field-cap','sentinel-helm','filter-hood','storm-crown','pressure-focus','thermal-prism','pressure-suit','cooling-jacket','rime-boots','thermal-boots','pressure-gloves','thermal-gloves','turbine-heart','cooling-core','pressure-belt','valve-belt'])assert(fs.statSync(new URL('../assets/items/'+name+'.webp',import.meta.url)).size>1000);const enemies=JSON.parse(fs.readFileSync(new URL('../assets/expedition/enemies-v8.json',import.meta.url)));assert.deepEqual(Object.keys(enemies),Object.keys(V8_ENEMIES));for(const spec of Object.values(enemies)){assert.equal(spec.frames.length,4);assert(spec.frames.every(f=>f.anchor.join(',')===spec.frames[0].anchor.join(',')));}});
console.log(`\n${count} v8 equipment, chapter, AI and progression checks passed.`);
